---
sidebar: sidebar 
permalink: learn/azure-storage.html 
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance 
summary: Astra Control Service使用Azure NetApp Files 支援功能作為Azure Kubernetes Service（KS）叢集的儲存後端。您應該瞭解如何選擇儲存類別和持續磁碟區大小、以協助您達成效能目標。 
---
= 適用於高峰叢集的儲存類別和PV大小
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control Service 支援 Azure NetApp Files 、 Azure 託管磁碟或 NetApp Cloud Volumes ONTAP 作為 Azure Kubernetes 服務（ aks ）叢集的儲存後端。



== Azure NetApp Files

Astra Control Service支援Azure NetApp Files 將支援用作Azure Kubernetes Service（KS）叢集的儲存後端。您應該瞭解如何選擇儲存類別和持續磁碟區大小、以協助您達成效能目標。



=== 服務層級與儲存類別

支援三種服務層級：超儲存設備、優質儲存設備和標準儲存設備。Azure NetApp Files每個服務層級都是針對不同的效能需求而設計：

超儲存設備:: 每1 TiB可提供高達128 MIB/s的處理量。
頂級儲存設備:: 每1 TiB可提供高達64 MIB/s的處理量。
標準儲存設備:: 每1 TiB可提供高達16 MIB/s的處理量。


這些服務層級是容量集區的屬性。您需要為要搭配Kubernetes叢集使用的每個服務層級設定容量資源池。 link:../get-started/set-up-microsoft-azure-with-anf.html["瞭解如何設定容量資源池"]。

Astra Control Service使用這些服務層級做為持續磁碟區的儲存類別。當您將Kubernetes叢集新增至Astra Control Service時、系統會提示您選擇「Ultra」、「Premium」或「Standard」作為預設儲存類別。儲存類別名稱為_NetApp-anf-perf-ulu_、_NetApp-anf-perf-pPremium _和_NetApp-anf-perf-Standard_。

https://["如需深入瞭解Azure NetApp Files 這些服務層級、請參閱《The》（英文）"^]。



=== 持續的Volume大小與效能

如上所述、每個服務層級的處理量是以已配置容量的1 TiB為單位。這表示較大的磁碟區可提供較佳的效能。因此、您在配置磁碟區時、應同時考量容量和效能需求。



=== 最小Volume大小

Astra Control Service會使用最小100 GiB的磁碟區大小來配置持續磁碟區、即使PVC要求較小的磁碟區大小也一樣。例如、如果Helm圖表中的永久虛擬磁碟要求6 GiB、Astra Control Service會自動配置100 GiB磁碟區。



=== 應用程式備份

如果您備份位於 Azure NetApp Files 儲存設備上的應用程式、 Astra Control Service 會自動暫時擴充容量池。備份完成後、 Astra Control Service 會將容量資源池縮減至先前的大小。視您的 Azure 訂閱而定、可能會在發生這種情況時產生儲存費用。您可以在 * 活動 * 頁面事件記錄中查看容量集區調整大小事件的歷程記錄。

如果容量集區超過 Azure 訂閱在調整大小作業期間所允許的最大大小、則備份作業將會失敗、並從 Azure API 觸發警告。



== Azure託管磁碟

Astra Control Service可以使用Container Storage Interface（SCSI）驅動程式、將Azure託管磁碟當作儲存後端來進行介面。此服務提供由Azure管理的區塊層級儲存設備。

https://["深入瞭解Azure託管磁碟"^]。



== NetApp Cloud Volumes ONTAP

如需設定NetApp Cloud Volumes ONTAP 產品的詳細資訊、包括效能建議、請造訪 https://["NetApp Cloud Volumes ONTAP 產品文件"^]。
