---
sidebar: sidebar 
permalink: learn/validated-vs-standard.html 
keywords: supported apps 
summary: 您可以將兩種應用程式帶入Astra Control、已驗證和Standard。瞭解這兩種類別之間的差異、以及對專案和策略的潛在影響。 
---
= 已驗證與標準應用程式的比較
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


Astra Control有兩種應用程式可供選擇：已驗證且符合標準。瞭解這兩種類別之間的差異、以及對專案和策略的潛在影響。


NOTE: 這兩種類別很容易想像為「支援」和「不支援」。 但如您所見、Astra Control中沒有「不受支援」的應用程式。您可以將任何應用程式新增至Astra Control、不過相較於標準應用程式、已驗證的應用程式在Astra Control工作流程中建置了更多基礎架構。



== 已驗證的應用程式

Astra Control已驗證的應用程式包括：

* MySQL 8.0.25
* MariaDB 10.5.9
* PostgreSQL 11.12
* Jenkins 2.277.4 LTS和2.289.1 LTS


通過驗證的應用程式清單代表Astra Control所識別的應用程式。Astra Control團隊已分析並確認這些應用程式已經過完整測試、可進行還原。Astra Control會執行自訂工作流程、協助確保快照與備份的應用程式層級一致性。

如果應用程式已通過驗證、Astra Control團隊已找出並實作步驟、以便在執行快照之前先停止應用程式、以取得應用程式一致的快照。例如、當Astra Control備份PostgreSQL資料庫時、它會先使資料庫靜止不動。備份完成後、Astra Control會將資料庫還原為正常作業。

無論您使用哪種類型的Astra Control應用程式、請務必自行測試備份與還原工作流程、確保您能夠滿足災難恢復需求。



== 標準應用程式

其他應用程式（包括自訂程式）則視為標準應用程式。您可以透過Astra Control新增及管理標準應用程式。您也可以建立基本的損毀一致快照、以及標準應用程式的備份。不過、這些應用程式尚未經過完整測試、無法將應用程式還原至原始狀態。


TIP: Astra Control本身並非標準應用程式、而是「系統應用程式」。 依預設、Astra Control本身不會顯示用於管理。您不應嘗試自行管理Astra Control。
