---
sidebar: sidebar 
permalink: solutions/jenkins-deploy-from-helm-chart.html 
keywords: helm, jenkins, deploy apps, deploy jenkins, bitnami, helm chart, astra, astra control, kubernetes 
summary: 從Bitnami Helm圖表瞭解如何部署Jenkins。在叢集上部署Jenkins之後、您可以向Astra Control註冊應用程式。 
---
= 從Helm圖表部署Jenkins
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/solutions/


瞭解如何從部署Jenkins https://bitnami.com/stack/jenkins/helm["Bitnami Helm圖表"^]。在叢集上部署Jenkins之後、您可以向Astra Control註冊應用程式。

Jenkins是Astra Control經過驗證的應用程式。

* https://docs.netapp.com/us-en/astra/learn/validated-vs-standard.html["瞭解Astra Control Service中已驗證的應用程式與標準應用程式之間的差異"^]。
* https://docs.netapp.com/us-en/astra-control-center/concepts/validated-vs-standard.html["瞭解Astra Control Center中已驗證的應用程式與標準應用程式之間的差異"^]。


這些指示適用於Astra Control Service和Astra Control Center。


NOTE: 從Google Marketplace部署的應用程式尚未通過驗證。有些使用者回報在部署PostgreSQL、MariaDB和MySQL的Google Marketplace時發生探索和/或備份問題。



== 需求

* 已新增至Astra Control的叢集。
+

NOTE: 對於Astra Control Center、您可以先將叢集新增至Astra Control Center、或先新增應用程式。

* 已更新版本的Helm（3.2以上版本）和Kubectl、安裝在本機機器上、且叢集的Kubeconfig適當


Astra Control目前不支援 https://plugins.jenkins.io/kubernetes/["適用於Jenkins的Kubernetes外掛程式"^]。您可以在Kubernetes叢集中執行Jenkins、而無需外掛程式。外掛程式可擴充至Jenkins叢集。



== 安裝Jenkins

此程序的兩項重要注意事項：

* 您必須在叢集新增至Astra Control Service之後部署應用程式、而非之前。Astra Control Center會在叢集新增至Astra Control Center之前或之後接受應用程式。
* 您必須將Helm圖表部署在預設名稱空間以外的名稱空間。


.步驟
. 新增Bitnami圖表repo：
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. 建立「Jenkins’命名空間、然後使用以下命令將Jenkins部署到其中：
+
[listing]
----

helm install <name> bitnami/jenkins –-namespace <namespace> --create-namespace
–-set global.storageClass=<storage_class_name>
----
+

NOTE: 如果磁碟區大小已變更、請使用Kibibyte（Ki）、Mebibyte（Mi）或Gibibyte（Gi）單位。

+
您只需在下列情況下定義儲存類別：

+
** 您使用的是Astra Control Service、不想使用預設的儲存類別。
** 您正在使用Astra Control Center、但尚未將叢集匯入Astra Control Center。或者、您已匯入叢集、但不想使用預設的儲存類別。




這會執行下列動作：

* 建立命名空間。
* 設定正確的儲存類別。


在Pod上線後、您可以使用Astra Control來管理應用程式。Astra Control可讓您管理命名空間層級的應用程式、或是使用Helm標籤。
