---
sidebar: sidebar 
permalink: solutions/mysql-deploy-from-helm-chart.html 
keywords: helm, mysql, helm chart, deploy mysql, astra, astra control, kubernetes 
summary: 從Bitnami Helm圖表中瞭解如何部署MySQL。在Kubernetes叢集上部署MySQL之後、您可以使用Astra Control來管理應用程式。 
---
= 從Helm圖表部署MySQL
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


瞭解如何從部署MySQL https://bitnami.com/stack/mysql/helm["Bitnami Helm圖表"^]。在Kubernetes叢集上部署MySQL之後、您可以使用Astra Control來管理應用程式。

MySQL是通過Astra Control驗證的應用程式。

* https://docs.netapp.com/us-en/astra/learn/validated-vs-standard.html["瞭解Astra Control Service中已驗證的應用程式與標準應用程式之間的差異"^]。
* https://docs.netapp.com/us-en/astra-control-center/concepts/validated-vs-standard.html["瞭解Astra Control Center中已驗證的應用程式與標準應用程式之間的差異"^]。


這些指示適用於Astra Control Service和Astra Control Center。


NOTE: 從Google Marketplace部署的應用程式尚未通過驗證。有些使用者回報在部署PostgreSQL、MariaDB和MySQL的Google Marketplace時發生探索和/或備份問題。



== 需求

* 已新增至Astra Control的叢集。
+

NOTE: 對於Astra Control Center、您可以先將叢集新增至Astra Control Center、或先新增應用程式。

* 已更新版本的Helm（3.2以上版本）和Kubectl、安裝在本機機器上、且叢集的Kubeconfig適當




== 安裝MySQL

此程序的兩項重要注意事項：

* 您必須在叢集新增至Astra Control Service之後部署應用程式、而非之前。Astra Control Center會在叢集新增至Astra Control Center之前或之後接受應用程式。
* 建議您將Helm圖表部署在預設名稱空間以外的名稱空間。


.步驟
. 新增Bitnami圖表repo：
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. 使用以下命令部署MySQL：
+
[listing]
----
Helm install <name> --namespace <namespace> --create-namespace -–set persistence.storageClass=<storage_class>
----
+

NOTE: 如果磁碟區大小已變更、請使用Kibibyte（Ki）、Mebibyte（Mi）或Gibibyte（Gi）單位。

+
您只需在下列情況下定義儲存類別：

+
** 您使用的是Astra Control Service、不想使用預設的儲存類別。
** 您正在使用Astra Control Center、但尚未將叢集匯入Astra Control Center。或者、您已匯入叢集、但不想使用預設的儲存類別。




這會執行下列動作：

* 建立命名空間。
* 在命名空間上部署MySQL。


在Pod上線後、您可以使用Astra Control來管理應用程式。Astra Control可讓您以應用程式名稱、命名空間層級或使用掌舵標籤來管理應用程式。
