---
sidebar: sidebar 
permalink: use/clone-apps.html 
keywords: clone app, clone storage, clone persistent storage, clone data, move workload, clone data, migrate data, data migration, move storage, move application, move data, migrate storage class 
summary: 複製現有的應用程式、在相同的Kubernetes叢集或其他叢集上建立複製的應用程式。如果您需要將應用程式和儲存設備從一個Kubernetes叢集移至另一個叢集、複製作業將有助於您。例如、您可能想要透過CI CD傳輸途徑和Kubernetes命名空間來移動工作負載。 
---
= 複製及移轉應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以複製現有的應用程式、在相同的Kubernetes叢集或其他叢集上建立複製的應用程式。當Astra Control複製應用程式時、會建立應用程式組態和持續儲存的複本。

如果您需要將應用程式和儲存設備從一個Kubernetes叢集移至另一個叢集、複製作業將有助於您。例如、您可能想要透過CI/CD傳輸途徑和Kubernetes命名空間來移動工作負載。


NOTE: 如果您將命名空間篩選器新增至執行掛勾、而執行還原或複製作業之後執行、且還原或複製來源與目的地位於不同的命名空間、則命名空間篩選器只會套用至目的地命名空間。

.開始之前
* * 檢查目的地 Volume * ：如果您複製到不同的儲存類別、請確定儲存類別使用相同的持續磁碟區存取模式（例如 ReadWriteMany ）。如果目的地持續磁碟區存取模式不同、則複製作業將會失敗。例如、如果來源持續性磁碟區使用 rwx 存取模式、請選取無法提供 rwx 的目的地儲存類別、例如 Azure Managed Disks 、 AWS EBS 、 Google Persistent Disk 或 `ontap-san`，將導致克隆操作失敗。如需持續磁碟區存取模式的詳細資訊、請參閱 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes["Kubernetes"^] 文件。
* 若要將應用程式複製到不同的叢集、您必須確定已為包含來源叢集的雲端執行個體指派預設儲存區。如果來源雲端執行個體沒有預設的儲存區集、跨叢集複製作業將會失敗。
* 在複製作業期間、需要IngresClass資源或Webhooks才能正常運作的應用程式、不得在目的地叢集上定義這些資源。


.複製限制
* *明確的儲存類別*：如果您部署的應用程式已明確設定儲存類別、而且需要複製應用程式、則目標叢集必須具有原本指定的儲存類別。將具有明確設定儲存類別的應用程式複製到沒有相同儲存類別的叢集、將會失敗。
* * ONTAP NAS 經濟型應用程式 * ：如果應用程式的儲存類別有支援、您就無法使用複製作業 `ontap-nas-economy` 驅動程式：不過、您可以 link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["啟用 ONTAP NAS 經濟營運的備份與還原"]。
* * Clone與使用者限制*：任何具有命名空間名稱/ ID或命名空間標籤限制的成員使用者、都可以將應用程式複製或還原至同一叢集上的新命名空間、或是組織帳戶中的任何其他叢集。不過、相同的使用者無法存取新命名空間中的複製或還原應用程式。在複製或還原作業建立新命名空間之後、帳戶管理員 / 擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以授予新命名空間的存取權。
* * Clones使用預設值區段*：
+
** 在應用程式備份或應用程式還原期間、您可以指定要使用的儲存區。當您在叢集之間複製時、需要指定預設的儲存區、但在同一個叢集內複製時、指定儲存區是選擇性的。
** 當您跨叢集複製時、包含實體複製作業來源叢集的雲端執行個體必須具有預設的儲存區集。
** 沒有選項可變更實體複本的儲存區。如果您想要控制所使用的儲存桶、您也可以選擇 link:../use/manage-buckets.html#edit-a-bucket["變更庫位預設值"] 或執行 link:../use/protect-apps.html#create-a-backup["備份"] 接著是A link:../use/restore-apps.html["還原"] 獨立提供。


* *使用Jenkins CI*：如果您複製由操作人員部署的Jenkins CI執行個體、則必須手動還原持續性資料。這是應用程式部署模式的限制。


.步驟
. 選擇*應用程式*。
. 執行下列其中一項：
+
** 在所需應用程式的*「Actions」（動作）欄中、選取「Options」（選項）功能表。
** 選取所需應用程式的名稱、然後選取頁面右上角的狀態下拉式清單。


. 選擇* Clone（克隆）*。
. 指定實體複本的詳細資料：
+
** 輸入名稱。
** 選擇要複製的目的地叢集。
** 輸入複本的目的地命名空間。與應用程式相關聯的每個來源命名空間都會對應至目的地命名空間。
+

NOTE: Astra Control會在複製作業中建立新的目的地命名空間。您指定的目的地命名空間不得已存在於目的地叢集上。

** 選擇*下一步*。
** 選擇保留與應用程式相關的原始儲存類別、或選擇不同的儲存類別。
+

NOTE: 您可以將應用程式的儲存類別移轉至原生雲端供應商儲存類別或其他支援的儲存類別、然後從以作為後盾的儲存類別移轉應用程式 `ontap-nas-economy` 以作為後盾的儲存類別 `ontap-nas` 在同一個叢集上、或是將應用程式複製到另一個叢集、並以儲存類別為後盾 `ontap-nas-economy` 驅動程式：

+

NOTE: 如果您選取不同的儲存類別、而此儲存類別在還原時並不存在、則會傳回錯誤。



. 選擇*下一步*。
. 檢閱有關複本的資訊、然後選取* Clone（複製）*。


.結果
Astra Control會根據您提供的資訊來複製應用程式。當有新的應用程式複製時、複製作業會成功完成 `Healthy` 請在「*應用程式*」頁面上說明。

在複製或還原作業建立新命名空間之後、帳戶管理員 / 擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以授予新命名空間的存取權。
