---
sidebar: sidebar 
permalink: use/clone-apps.html 
keywords: clone app, clone storage, clone persistent storage, clone data, move workload, clone data, migrate data, data migration, move storage, move application, move data 
summary: 複製現有的應用程式、在相同的Kubernetes叢集或其他叢集上建立複製的應用程式。如果您需要將應用程式和儲存設備從一個Kubernetes叢集移至另一個叢集、複製作業將有助於您。例如、您可能想要透過CI CD傳輸途徑和Kubernetes命名空間來移動工作負載。 
---
= 複製及移轉應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以複製現有的應用程式、在相同的Kubernetes叢集或其他叢集上建立複製的應用程式。當Astra Control複製應用程式時、會建立應用程式組態和持續儲存的複本。

如果您需要將應用程式和儲存設備從一個Kubernetes叢集移至另一個叢集、複製作業將有助於您。例如、您可能想要透過CI/CD傳輸途徑和Kubernetes命名空間來移動工作負載。

.您需要的產品
* 若要將應用程式複製到不同的叢集、您必須確保包含來源和目的地叢集（如果它們不同）的雲端執行個體具有預設的儲存區。您必須為每個雲端執行個體指派預設儲存區。
* 在複製作業期間、需要IngresClass資源或Webhooks才能正常運作的應用程式、不得在目的地叢集上定義這些資源。


.複製限制
* *明確的儲存類別*：如果您部署的應用程式已明確設定StorageClass、且需要複製應用程式、則目標叢集必須具有原本指定的StorageClass。將具有明確設定StorageClass的應用程式複製到沒有相同StorageClass的叢集、將會失敗。
* * Clone與使用者限制*：任何具有命名空間名稱/ ID或命名空間標籤限制的成員使用者、都可以將應用程式複製或還原至同一叢集上的新命名空間、或是組織帳戶中的任何其他叢集。不過、相同的使用者無法存取新命名空間中的複製或還原應用程式。在複製或還原作業建立新命名空間之後、帳戶管理員/擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以便授予新命名空間的存取權。
* * Clones使用預設值區段*：
+
** 在應用程式備份或應用程式還原期間、您可以指定要使用的儲存區。當您在叢集之間複製時、需要指定預設的儲存區、但在同一個叢集內複製時、指定儲存區是選擇性的。
** 當您跨叢集複製時、包含實體複製作業來源叢集的雲端執行個體必須具有預設的儲存區集。
** 沒有選項可變更實體複本的儲存區。如果您想要控制所使用的儲存桶、您也可以選擇 link:../use/manage-buckets.html#edit-a-bucket["變更庫位預設值"] 或執行 link:../use/protect-apps.html#create-a-backup["備份"] 接著是A link:../use/restore-apps.html["還原"] 獨立提供。


* *使用Jenkins CI*：如果您複製由操作人員部署的Jenkins CI執行個體、則必須手動還原持續性資料。這是應用程式部署模式的限制。


.步驟
. 選擇*應用程式*。
. 執行下列其中一項：
+
** 在所需應用程式的*「Actions」（動作）欄中、選取「Options」（選項）功能表。
** 選取所需應用程式的名稱、然後選取頁面右上角的狀態下拉式清單。


. 選擇* Clone（克隆）*。
. 指定實體複本的詳細資料：
+
** 輸入名稱。
** 選擇要複製的目的地叢集。
** 輸入複本的目的地命名空間。與應用程式相關聯的每個來源命名空間都會對應至目的地命名空間。
+

NOTE: Astra Control會在複製作業中建立新的目的地命名空間。您指定的目的地命名空間不得已存在於目的地叢集上。

** 選擇*下一步*。
** 選擇是要從現有的快照或備份建立複本。如果您未選取此選項、Astra Control會從應用程式的目前狀態建立複本。
+
*** 如果您選擇從現有的快照或備份複製、請選擇您要使用的快照或備份。




. 選擇*下一步*。
. 檢閱有關複本的資訊、然後選取* Clone（複製）*。


.結果
Astra Control會根據您提供的資訊來複製應用程式。當有新的應用程式複製時、複製作業會成功完成 `Healthy` 請在「*應用程式*」頁面上說明。

在複製或還原作業建立新命名空間之後、帳戶管理員/擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以便授予新命名空間的存取權。
