---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 隨時從您的帳戶新增及移除雲端供應商認證資料。Astra Control會使用這些認證資料代您配置資源。 
---
= 新增及移除認證資料
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


隨時從您的帳戶新增及移除雲端供應商認證資料。Astra Control會使用這些認證資料來探索Kubernetes叢集、叢集上的應用程式、並代表您配置資源。

請注意、Astra Control中的所有使用者都共用相同的認證集。



== 新增認證資料

將認證新增至Astra Control的最常見方法是管理叢集、但您也可以從「帳戶」頁面新增認證。然後、當您管理額外的Kubernetes叢集時、便可選擇認證資料。

.您需要的是 #8217 ；需要的是什麼
* 若為GKE、您應該擁有具有所需權限之服務帳戶的服務帳戶金鑰檔案。 link:../get-started/set-up-google-cloud.html["瞭解如何設定服務帳戶"]。
* 若為高效能、您應該擁有Json檔案、其中應包含建立服務主體時Azure CLI的輸出。 link:../get-started/set-up-microsoft-azure-with-anf.html["瞭解如何設定服務主體"]。
+
如果您未將Azure訂閱ID新增至Json檔案、您也需要Azure訂閱ID。



.步驟
. 選擇*帳戶>認證*。
. 選取*新增認證*。
. 選擇* Microsoft Azure *或* Google Cloud Platform *。
. 在Astra Control中輸入認證資料的名稱、以區分這些認證與其他認證資料。
. 提供必要的認證資料。
+
.. * Microsoft Azure *：上傳Json檔案或從剪貼簿貼上Json檔案的內容、以提供Astra Control有關Azure服務主體的詳細資料。
+
當您建立服務主體時、Json檔案應包含Azure CLI的輸出。它也可以包含您的訂閱ID、以便自動新增至Astra Control。否則、您必須在提供Json之後手動輸入ID。

.. * Google Cloud Platform *：上傳檔案或從剪貼簿貼上內容、以提供Google Cloud服務帳戶金鑰檔案。


. 選取*新增認證*。


您現在可以在將叢集新增至Astra Control時、選取認證資料。



== 移除認證資料

隨時從帳戶移除認證資料。您只能在之後移除認證 link:unmanage.html["取消管理所有叢集"]。


NOTE: 您新增至Astra Control的第一組認證資料一律使用中、因為Astra Control使用認證資料來驗證備份儲存區。最好不要移除這些認證資料。

.步驟
. 選擇*帳戶>認證*。
. 選取您要移除之認證資料的「*狀態*」欄中的下拉式清單。
. 選擇*移除*。
. 輸入要確認刪除的認證資料名稱、然後選取*是、移除認證*。


Astra Control會從帳戶移除認證資料。
