---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: invite users, add users, remove users, delete users 
summary: 邀請使用者加入您的Astra Control帳戶、並移除不應再存取您帳戶的使用者。 
---
= 邀請及移除使用者
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
邀請使用者加入您的Astra Control帳戶、並移除不應再擁有帳戶存取權的使用者。



== 邀請使用者

帳戶擁有者和管理員可以邀請其他使用者加入Astra Control帳戶。

.步驟
. 請確定使用者擁有 link:../get-started/register.html["Cloud Central登入"]。
. 選擇*帳戶*。
. 在*使用者*索引標籤中、選取*邀請*。
. 輸入使用者名稱、電子郵件地址及其角色。
+
請注意下列事項：

+
** 電子郵件地址必須與使用者用來註冊Cloud Central的電子郵件地址相符。
** 每個角色都提供下列權限：
+
*** *擁有者*具有管理權限、可刪除帳戶。
*** *管理*具有成員權限、可以邀請其他使用者。
*** *成員*可以完全管理應用程式和叢集。
*** *檢視器*可以檢視資源。




. 若要新增限制給具有成員或檢視者角色的使用者、請啟用*限制角色限制*核取方塊。
+
如需新增限制的詳細資訊、請參閱 link:manage-roles.html["管理角色"]。

. 若要邀請其他使用者、請選取*新增其他使用者*、然後輸入新使用者的資訊。
+
您一次最多可邀請10位使用者。您可以在「*邀請使用者*」對話方塊的左側、在您要邀請的使用者之間瀏覽。

. 選擇*邀請使用者*。


.結果
使用者將會收到一封電子郵件、邀請他們加入您的帳戶。



== 變更使用者角色

帳戶擁有者可以變更所有使用者的角色、而帳戶管理員可以變更具有管理員、成員或檢視者角色的使用者角色。

.步驟
. 選擇*帳戶*。
. 在「*使用者*」索引標籤中、選取使用者「*動作*」欄中的功能表。
. 選擇*編輯角色*。
. 選取新角色。
. 若要新增限制給具有成員或檢視者角色的使用者、請啟用*限制角色限制*核取方塊。
+
如需新增限制的詳細資訊、請參閱 link:manage-roles.html["管理角色"]。

. 選擇* Confirm（確認）*。


.結果
Astra Control會根據您選取的新角色來更新使用者權限。



== 移除使用者

擁有者角色的使用者可以隨時從帳戶中移除其他使用者。

.步驟
. 選擇*帳戶*。
. 在*使用者*索引標籤中、選取您要移除的使用者。
. 在「*動作*」欄中選取功能表、然後選取「*移除使用者*」。
. 出現提示時、請輸入「移除」確認刪除、然後選擇*是、移除使用者*。


.結果
Astra Control會將使用者從帳戶中移除。
