---
sidebar: sidebar 
permalink: use/manage-roles.html 
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint, constraints 
summary: 瞭解如何藉由新增角色限制來管理使用者角色。 
---
= 管理角色
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以新增命名空間限制、並將使用者角色限制在這些限制中、藉此管理角色。這可讓您控制組織內資源的存取。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理角色。



== 將命名空間限制新增至角色

管理員或擁有者使用者可以新增命名空間限制。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 在「*動作*」欄中、選取具有「成員」或「檢視者」角色的使用者功能表按鈕。
. 選擇*編輯角色*。
. 啟用「限制角色*」核取方塊。
+
此核取方塊僅適用於「成員」或「檢視者」角色。您可以從*角色*下拉式清單中選取不同的角色。

. 選取*新增限制*。
+
您可以依命名空間或命名空間標籤檢視可用限制清單。

. 在*限制類型*下拉式清單中、視命名空間的設定方式而定、選取* Kubernetes命名空間*或* Kubernetes命名空間標籤*。
. 從清單中選取一或多個命名空間或標籤、以構成限制、限制角色只能使用這些命名空間。
. 選擇* Confirm（確認）*。
+
「*編輯角色*」頁面會顯示您為此角色選擇的限制清單。

. 選擇* Confirm（確認）*。
+
在「*帳戶*」頁面上、您可以在「*角色*」欄中檢視任何成員或檢視者角色的限制條件。




NOTE: 如果您啟用角色的限制、並選取* Confirm（確認）*而不新增任何限制、則該角色會被視為具有完整限制（該角色無法存取指派給命名空間的任何資源）。



== 從角色移除命名空間限制

管理員或擁有者使用者可以從角色移除命名空間限制。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 在「*動作*」欄中、選取具有作用中限制之「成員」或「檢視者」角色的使用者功能表按鈕。
. 選擇*編輯角色*。
+
「*編輯角色*」對話方塊會顯示角色的作用中限制。

. 選取您需要移除之限制右側的* X*。
. 選擇* Confirm（確認）*。




== 以取得更多資訊

* link:../learn/user-roles-namespaces.html["使用者角色和命名空間"]

