---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: 透過新增其他儲存區、以及變更雲端供應商叢集的預設儲存區、來管理Astra用於備份與複製的儲存區。 
---
= 管理儲存庫
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以管理Astra用於備份與複製的儲存區。您可以在雲端執行個體中新增其他儲存區、移除現有的儲存區、以及變更Kubernetes叢集的預設儲存區。

只有擁有者和管理員可以管理儲存區。



== Astra Control如何使用鏟斗

當您開始管理雲端執行個體的第一個Kubernetes叢集時、Astra Control Service會為其建立初始儲存庫 link:manage-cloud-instances.html["雲端執行個體"^]。

您可以手動將儲存區指定為雲端執行個體的預設儲存區。如果您這麼做、Astra Control Service預設會將此儲存區用於您在該雲端執行個體的任何託管叢集上所建立的備份與複本（您可以選取不同的儲存庫進行備份）。如果您從雲端執行個體中的任一託管叢集執行應用程式的即時複製到另一個叢集、Astra Control Service會使用來源雲端執行個體的預設儲存區來執行複製作業。

您可以為多個雲端執行個體設定相同的儲存區作為預設儲存區。

您可以在建立保護原則或啟動臨機操作備份時、從任何儲存區中進行選擇。


TIP: Astra Control Service會在開始備份或實體複本之前、先檢查目標儲存區是否可供存取。



== 檢視現有的貯體

檢視Astra Control Service可用的儲存庫清單、以判斷其狀態、並識別雲端執行個體的預設儲存庫（若已定義）。

桶可能具有下列任一狀態：

擱置中:: 新增儲存區之後、它會從擱置狀態開始、而Astra Control會發現它。
可用:: 此鏟斗可供Astra Control使用。
已移除:: 鏟斗目前無法運作。將滑鼠游標暫留在狀態圖示上、以找出問題所在。
+
--
如果某個儲存區處於「已移除」狀態、您仍可將其設為預設儲存區、並將其指派給保護排程。但如果儲存區在資料保護作業開始時未處於可用狀態、則該作業將會失敗。

--


.步驟
. 移至*鏟斗*。
+
隨即顯示Astra Control Service可用的貯體清單。





== 新增額外的儲存庫

您可以隨時新增其他庫位。這可讓您在建立保護原則或啟動臨機操作備份時、在儲存區之間進行選擇、並可讓您變更雲端執行個體使用的預設儲存區。

您可以新增下列類型的貯體：

* Amazon Web Services
* 一般S3
* Google Cloud Platform
* Microsoft Azure
* NetApp ONTAP 產品S3
* NetApp StorageGRID 產品S3


.您需要的產品
* 現有桶的名稱。
* 提供Astra Control Service所需權限來管理儲存庫的儲存庫認證。


ifdef::azure[]

* 如果您的目標是在Microsoft Azure：
+
** 此儲存區必須屬於名為_Astra備份rg-_的資源群組。
** 如果Azure儲存帳戶執行個體效能設定設為「Premium」、則「Premium帳戶類型」設定必須設為「區塊區塊區塊」。




endif::azure[]

.步驟
. 移至*鏟斗*。
. 選擇*「Add」（新增）*、然後依照提示新增儲存區。
+
** *類型*：選擇您的雲端供應商。
** *現有庫位名稱*：輸入庫位名稱。
** *說明*：選擇性地輸入桶的說明。




ifdef::azure[]

* *儲存帳戶*（僅限Azure）：輸入Azure儲存帳戶的名稱。此儲存區必須屬於名為_Astra備份rg-_的資源群組。


endif::azure[]

ifdef::aws[]

* * S3伺服器名稱或IP位址*（僅限AWS和S3儲存區類型）：輸入S3端點的完整網域名稱、此名稱對應於您所在的地區、不需要 `https://`。請參閱 https://docs.aws.amazon.com/general/latest/gr/s3.html["Amazon文件"^] 以取得更多資訊。


endif::aws[]

* *選取認證資料*：輸入提供Astra Control Service管理儲存庫所需權限的認證資料。您需要提供的資訊會因儲存區類型而異。
+
.. 選取*「Add*（新增*）」以新增儲存區。




.結果
Astra Control Service新增儲存庫。您現在可以在建立保護原則或執行臨機操作備份時選擇此儲存區。您也可以將此儲存區設為雲端執行個體的預設儲存區。



== 變更預設儲存區

您可以變更雲端執行個體的預設儲存區。Astra Control Service預設會將此儲存區用於備份與複製。每個雲端執行個體都有自己的預設儲存區。


NOTE: Astra Control不會自動指派任何雲端執行個體的預設儲存區。您需要手動設定雲端執行個體的預設儲存區、才能在兩個叢集之間執行應用程式複製作業。

.步驟
. 轉至* Cloud Instances *。
. 針對您要編輯的雲端執行個體、在* Actions *（動作*）欄中選取組態功能表。
. 選擇*編輯*。
. 在庫位清單中、選取您要為此雲端執行個體建立預設庫位的庫位。
. 選擇*更新*。




== 移除貯體

您可以移除不再使用或不健全的庫位。您可能會想要這麼做、讓物件存放區組態保持簡單且最新狀態。

您無法移除預設的儲存區。如果您要移除該儲存區、請先選取另一個儲存區做為預設值。

.您需要的產品
* 開始之前、您應檢查以確保此儲存區沒有執行中或已完成的備份。
* 您應該檢查以確保儲存庫不會用於任何排程的備份。


如果有、您將無法繼續。

.步驟
. 移至*鏟斗*。
. 從* Actions（操作）*功能表中、選取*移除*。
+

NOTE: Astra Control會先確保不會有使用儲存庫進行備份的排程原則、而且您要移除的儲存庫中沒有作用中的備份。

. 輸入「移除」以確認動作。
. 選擇*是、移除桶*。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/astra-automation/index.html["使用Astra Control API"^]

