---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: 透過新增其他儲存區、以及變更雲端供應商叢集的預設儲存區、來管理Astra用於備份與複製的儲存區。 
---
= 管理儲存庫
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


透過新增其他儲存區、以及變更雲端供應商Kubernetes叢集的預設儲存區、來管理Astra用於備份與複製的儲存區。

只有管理員可以新增及修改儲存區。



== Astra Control如何使用鏟斗

當您開始管理第一個Kubernetes叢集時、Astra Control Service會在與受管理叢集相同的地理區域中、為您的雲端供應商建立預設儲存區。

Astra Control Service使用此預設儲存區來進行您所建立的備份與複製。然後、您可以使用備份來還原及複製叢集之間的應用程式。

如果您在Astra Control Service中新增其他儲存庫、則可在建立保護原則時從這些儲存庫中選取。您也可以變更Astra Control Service用於臨機操作備份與複製的預設儲存區。您無法將儲存庫從一個雲端供應商複製到另一個雲端供應商。若要將資料從一個雲端供應商移轉至另一個雲端供應商、請改為複製相關的應用程式。


TIP: Astra Control Service會在開始備份或實體複本之前、先檢查目標儲存區是否可供存取。



== 檢視現有的貯體

檢視Astra Control Service可用的庫存箱清單、以判斷其狀態、並識別雲端供應商的預設庫存箱。

桶可能具有下列任一狀態：

擱置中:: 新增儲存區之後、它會從擱置狀態開始、而Astra Control則會第一次查看它。
可用:: 此鏟斗可供Astra Control使用。
已移除:: 鏟斗目前無法運作。將滑鼠游標暫留在狀態圖示上、以找出問題所在。
+
--
如果某個儲存區處於「已移除」狀態、您仍可將其設為預設儲存區、並將其指派給保護排程。但如果儲存區在資料保護作業開始時未處於可用狀態、則該作業將會失敗。

--


.步驟
. 在「*管理您的儲存設備*」下、選取「*桶*」。
+
顯示Astra Control Service可用的貯體清單。





== 新增額外的儲存庫

在雲端供應商開始管理叢集之後、您可以隨時新增其他資源庫。這可讓您在建立保護原則時、在儲存區之間進行選擇、並變更臨機操作備份與複製的預設儲存區。

請注意、Astra Control Service無法讓您在新增後移除庫位。

.您需要的是 #8217 ；需要的是什麼
* 雲端供應商中現有儲存庫的名稱。


ifdef::azure[]

* 如果您的儲存庫位於Azure、則必須屬於名為_Astra備份rg-_的資源群組。


endif::azure[]

.步驟
. 在「*管理您的儲存設備*」下、選取「*桶*」。
. 選擇*「Add」（新增）*、然後依照提示新增儲存區。
+
** *類型*：選擇您的雲端供應商。
+
您的雲端供應商只有在Astra Control Service開始管理在該雲端供應商中執行的叢集之後、才能使用。

** *現有庫位名稱*：輸入庫位名稱。
** *說明*：選擇性地輸入桶的說明。
** *將此儲存區設為此雲端的預設儲存區*：選擇是否要使用此儲存區做為臨機操作備份與複製的預設儲存區。
** *選取認證資料*：選擇提供Astra Control Service所需權限的認證資料、以管理儲存庫。


. 選取*「Add*（新增*）」以新增儲存區。


Astra Control Service新增額外的儲存庫。您現在可以在建立保護原則時選擇儲存庫。



== 變更預設儲存區

變更Astra Control Service用於備份與複製的預設儲存區。每個雲端供應商都有自己的預設儲存庫。

Astra Control Service使用雲端供應商的預設儲存庫進行臨機操作備份、如果您不選擇從現有備份複製、則可用於臨機操作複製。

.步驟
. 在「*管理您的儲存設備*」下、選取「*桶*」。
. 在* Actions *（動作*）欄中選取您要編輯的儲存區的下拉式清單。
. 選取*將此儲存區設為此雲端的預設儲存區*。
. 選擇*更新*。




== 移除貯體

您可以移除不再使用或不健全的庫位。您可能會想要這麼做、讓物件存放區組態保持簡單且最新狀態。

您無法移除預設的儲存區。如果您要移除該儲存區、請先選取另一個儲存區做為預設值。

.您需要的是 #8217 ；需要的是什麼
* 開始之前、您應檢查以確保此儲存區沒有執行中或已完成的備份。
* 您應該檢查以確保儲存庫不會用於任何排程的備份。


如果有、您將無法繼續。

.步驟
. 從左側導覽中選取*鏟斗*。
. 從* Actions（操作）*功能表中、選取*移除*。
+

NOTE: Astra Control會先確保不會有使用儲存庫進行備份的排程原則、而且您要移除的儲存庫中沒有作用中的備份。

. 輸入「移除」以確認動作。
. 選擇*是、移除桶*。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/astra-automation/index.html["使用Astra Control API"^]

