---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra Control可從快照或備份還原應用程式組態和持續儲存。持續儲存備份會從物件存放區傳輸、因此從現有備份還原將能最快完成。 
---
= 還原應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control可以從快照或備份還原應用程式。將應用程式還原至同一個叢集時、從現有的快照還原速度會更快。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以還原應用程式。


NOTE: 當您對使用NetApp ONTAP 還原的應用程式執行就地還原時、還原的應用程式所使用的空間可能會加倍。執行就地還原之後、請從還原的應用程式中移除任何不想要的快照、以釋放儲存空間。


NOTE: 如果您將命名空間篩選器新增至執行掛勾、而執行還原或複製作業之後執行、且還原或複製來源與目的地位於不同的命名空間、則命名空間篩選器只會套用至目的地命名空間。

.關於這項工作
* *先保護應用程式*：強烈建議您在還原應用程式之前、先擷取應用程式的快照或備份應用程式。這可讓您在還原失敗時、從快照或備份進行複製。
* *檢查目的地儲存類別*：如果還原至不同的叢集、請確定目的地叢集的儲存類別使用與來源叢集上儲存類別相同的持續磁碟區存取模式（例如ReadWriteMany）。如果目的地持續磁碟區存取模式不同、還原作業將會失敗。


.步驟
. 選取*應用程式*、然後選取應用程式名稱。
. 選擇*資料保護*。
. 如果您想要從快照還原、請保持選取* Snapshot*。否則、請選取*備份*以從備份還原。
. 從您要還原之快照或備份的「*動作*」欄中的「選項」功能表中、選取「*還原應用程式*」。
. 選擇還原類型：
+
** *還原至原始命名空間*：使用此程序可將應用程式就地還原至原始叢集。
+
[CAUTION]
====
在與其他應用程式共用資源的應用程式上執行就地還原作業、可能會產生非預期的結果。在其中一個應用程式上執行就地還原時、應用程式之間共享的任何資源都會被取代。

====
+
... 選取要用來就地還原應用程式的快照、此快照會將應用程式還原為舊版本身。
... 選擇*下一步*。
+

NOTE: 如果還原至先前刪除的命名空間、則會在還原程序中建立名稱相同的新命名空間。任何在先前刪除命名空間中擁有管理應用程式權限的使用者、都必須手動還原新重新建立命名空間的權限。

... 檢閱還原動作的詳細資料、輸入「還原」、然後選取*還原*。


** *還原至新命名空間*：使用此程序可將應用程式還原至其他叢集、或從來源還原具有不同命名空間的叢集。
+
... 針對您要還原的應用程式、選擇目的地叢集。
... 為每個與應用程式相關聯的來源命名空間輸入目的地命名空間。
+

NOTE: Astra Control會在此還原選項中建立新的目的地命名空間。您指定的目的地命名空間不得已存在於目的地叢集上。

... 選擇*下一步*。
... 選取要用來還原應用程式的快照。
... 選擇*下一步*。
... 檢閱還原動作的詳細資料、然後選取*還原*。






.結果
Astra Control會根據您提供的資訊還原應用程式。如果您就地還原應用程式、現有持續磁碟區的內容會由還原應用程式的持續磁碟區內容取代。


NOTE: 任何具有命名空間限制的成員使用者、都可以使用命名空間名稱/ ID或命名空間標籤、將應用程式複製或還原到同一個叢集上的新命名空間、或是組織帳戶中的任何其他叢集。不過、相同的使用者無法存取新命名空間中的複製或還原應用程式。在複製或還原作業建立新命名空間之後、帳戶管理員/擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以便授予新命名空間的存取權。
