---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra Control可從快照或備份還原應用程式組態和持續儲存。持續儲存備份會從物件存放區傳輸、因此從現有備份還原將能最快完成。 
---
= 還原應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control可以從快照或備份還原應用程式。將應用程式還原至同一個叢集時、從現有的快照還原速度會更快。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以還原應用程式。


NOTE: 任何具有命名空間名稱/ ID或命名空間標籤限制的成員使用者、都可以將應用程式複製或還原到同一個叢集上的新命名空間、或是組織帳戶中的任何其他叢集。不過、相同的使用者無法存取新命名空間中的複製或還原應用程式。在複製或還原作業建立新命名空間之後、帳戶管理員/擁有者可以編輯成員使用者帳戶、並更新受影響使用者的角色限制、以便授予新命名空間的存取權。

.步驟
. 選取*應用程式*、然後選取託管應用程式的名稱。
. 選擇*資料保護*。
. 如果您想要從快照還原、請保持選取* Snapshot*。否則、請選取*備份*以從備份還原。
. 在* Actions *（操作*）欄中選取您要還原的快照或備份下拉式清單。
. 選取*還原應用程式*。
. *還原詳細資料*：指定還原應用程式的詳細資料。若要就地還原應用程式（將應用程式還原為本身的舊版）、請選擇目前執行的相同命名空間和目的地叢集：
+
** 輸入應用程式的命名空間。
** 選擇應用程式的目的地叢集。
** 按一下* Review *。
+

NOTE: 如果還原至先前刪除的命名空間、則會在還原程序中建立名稱相同的新命名空間。任何在先前刪除命名空間中擁有管理應用程式權限的使用者、都必須手動還原新重新建立命名空間的權限。



. *還原摘要*：檢閱還原動作的詳細資料、輸入「還原」、然後選取*還原*。


Astra Control會根據您提供的資訊還原應用程式。如果您就地還原應用程式、則會刪除並重新建立相關的持續磁碟區。
