---
sidebar: sidebar 
permalink: get-started/add-private-self-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。 
---
= 將私有自我管理叢集新增至 Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。

自我管理的叢集是您直接進行資源配置與管理的叢集。Astra Control Service支援在公有雲環境中執行的自我管理叢集。您可以上傳、將自我管理的叢集新增至Astra Control Service `kubeconfig.yaml` 檔案：您必須確保叢集符合此處列出的需求。



== 支援的 Kubernetes 發佈

您可以使用 Astra Control Service 來管理下列類型的私有、自我管理叢集：

|===
| Kubernetes 配送 | 支援的版本 


| Kubernetes （上游） | 1.26 至 1.28 


| Rancher Kubernetes引擎（RKE） | RKE 1.3 搭配 Rancher Manager 2.6
RKE 1.4 搭配 Rancher Manager 2.7
RKE 2 （ v1.24.x ）搭配 Rancher 2.6
RKE 2 （ v1.26.x ）搭配 Rancher 2.7 


| Red Hat OpenShift Container Platform | 4.11 至 4.13 
|===
這些指示假設您已經建立了私有叢集、並準備了安全的方法來遠端存取它。

您必須執行下列工作、才能將您的私有叢集新增至 Astra Control Service ：

. <<安裝 Astra Connector>>
. <<設定持續儲存>>
. <<將私有自我管理叢集新增至 Astra Control Service>>




== 安裝 Astra Connector

在新增私有叢集之前、您需要在叢集上安裝 Astra Connector 、以便 Astra Control 能夠與其通訊。請參閱 link:install-astra-connector.html["安裝 Astra Connector for Private 叢集"] 以取得相關指示。



== 設定持續儲存

設定叢集的持續儲存設備。如需設定持續儲存設備的詳細資訊、請參閱入門文件：

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["使用Azure NetApp Files 更新功能來設定Microsoft Azure"^]
* link:set-up-microsoft-azure-with-amd.html["使用Azure託管磁碟來設定Microsoft Azure"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["設定Amazon Web Services"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["設定Google Cloud"^]


endif::gcp[]



== 將私有自我管理叢集新增至 Astra Control Service

您現在可以將私有叢集新增至 Astra Control Service 。

.開始之前
[%collapsible%open]
====
自我管理的叢集是您直接進行資源配置與管理的叢集。Astra Control Service支援在公有雲環境中執行的自我管理叢集。您的自我管理叢集可以使用Astra Trident來與NetApp儲存服務建立連結、也可以使用Container Storage介面（SCSI）驅動程式來與Amazon Elastic Block Store（EBS）、Azure託管磁碟和Google持續磁碟建立連結。

Astra Control Service支援使用下列Kubernetes發佈版本的自我管理叢集：

* Red Hat OpenShift Container Platform
* Rancher Kubernetes引擎
* 上游Kubernetes


您的自我管理叢集必須符合下列需求：

* 叢集必須可透過網際網路存取。
* 如果您使用或打算使用已啟用SCSI驅動程式的儲存設備、則叢集上必須安裝適當的SCSI驅動程式。如需使用SCSI驅動程式來整合儲存設備的詳細資訊、請參閱儲存服務的說明文件。
* 您可以存取僅包含一個內容元素的叢集 kubeconfig 檔案。追蹤 link:create-kubeconfig.html["這些指示"^] 以產生 kubeconfig 檔案。
* 如果您要使用參考私有憑證授權單位（ CA ）的 kubeconfig 檔案來新增叢集、請將下列行新增至 `cluster` kubeconfig 檔案的一節。這可讓 Astra Control 新增叢集：
+
[listing]
----
insecure-skip-tls-verify: true
----
* *僅限Rancher *：在Rancher環境中管理應用程式叢集時、請在Rancher提供的Kusbeconfig檔案中修改應用程式叢集的預設內容、以使用控制面內容而非Rancher API伺服器內容。如此可減少Rancher API伺服器的負載、並改善效能。
* * Astra Trident * ：如果您使用或打算使用 NetApp 儲存設備、請確定您已安裝最新版本的 Astra Trident 。如果 Astra Trident 已安裝、 link:check-astra-trident-version.html["請檢查以確定其為最新版本"^]。
+

NOTE: 您可以 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["部署Astra Trident"^] 使用Trident運算子（手動或使用Helm圖表）或 `tridentctl`。在安裝或升級Astra Trident之前、請先檢閱 https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["支援的前端、後端及主機組態"^]。

+
** * 已設定 Astra Trident 儲存後端 * ：至少必須有一個 Astra Trident 儲存後端 https://docs.netapp.com/us-en/trident/trident-use/backends.html["已設定"^] 在叢集上。
** * 已設定的 Astra Trident 儲存類別 * ：至少必須有一個 Astra Trident 儲存類別 https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["已設定"^] 在叢集上。如果已設定預設儲存類別、請確定只有一個儲存類別具有該註釋。
** *已安裝並設定的Astra Trident Volume Snapshot控制器與Volume Snapshot類別*：Volume Snapshot控制器必須是 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["已安裝"^] 以便在Astra Control中建立快照。至少有一個Astra Trident `VolumeSnapshotClass` 過去了 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["設定"^] 由系統管理員執行。




====
* * Astra Control Provisioner* ：若要使用 Astra Control Provisioner 進階管理和儲存資源配置功能、而 Astra Control 使用者只能存取這些功能、您必須安裝 Astra Trident 23.10 或更新版本並啟用 link:../use/enable-acp.html["Astra Control Provisioner 功能"]。


.步驟
. 在儀表板上、選取*管理Kubernetes叢集*。
+
依照提示新增叢集。

. * 提供者 * ：選取 * 其他 * 索引標籤以新增自我管理叢集的詳細資料。
. *其他*：上傳以提供自我管理叢集的詳細資料 `kubeconfig.yaml` 檔案或貼上的內容 `kubeconfig.yaml` 檔案。
+

NOTE: 如果您自行建立 `kubeconfig` 檔案中、您應該只定義*一個*內容元素。請參閱 link:create-kubeconfig.html["這些指示"^] 以取得有關建立的資訊 `kubeconfig` 檔案：

. * 認證名稱 * ：為您上傳至 Astra Control 的自我管理叢集認證提供名稱。根據預設、認證名稱會自動填入為叢集名稱。
. * 私有路由識別碼 * ：輸入可從 Astra Connector 取得的私有路由識別碼。如果您透過查詢 Astra Connector `kubectl get astraconnector -n astra-connector` 命令時、私有路由識別碼稱為 `ASTRACONNECTORID`。
+

NOTE: 私有路由識別碼是與 Astra Connector 相關的名稱、可讓 Astra 管理私有 Kubernetes 叢集。在這種情況下、私有叢集是 Kubernetes 叢集、不會將其 API 伺服器暴露於網際網路上。

. 選擇*下一步*。
. （可選） * Storage* ：（可選）選擇您希望 Kubernetes 應用程式部署到此叢集的儲存類別、以供預設使用。
+
.. 若要為叢集選取新的預設儲存類別、請啟用 * 指派新的預設儲存類別 * 核取方塊。
.. 從清單中選取新的預設儲存類別。
+
[NOTE]
====
每個雲端供應商的儲存服務都會顯示下列價格、效能和恢復能力資訊：

ifdef::gcp[]

*** 適用於Google Cloud的解決方案：價格、效能和恢復能力資訊Cloud Volumes Service
*** Google持續磁碟：沒有可用的價格、效能或恢復能力資訊


endif::gcp[]

ifdef::azure[]

*** 支援：效能與恢復能力資訊Azure NetApp Files
*** Azure託管磁碟：不提供價格、效能或恢復能力資訊


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store：沒有可用的價格、效能或恢復能力資訊
*** Amazon FSX for NetApp ONTAP 不提供價格、效能或恢復能力資訊


endif::aws[]

*** NetApp Cloud Volumes ONTAP 產品：不提供價格、效能或恢復能力資訊


====
+
每個儲存類別都可以使用下列其中一項服務：





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]
* https://cloud.google.com/persistent-disk/["Google持續磁碟"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure託管磁碟"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon彈性區塊存放區"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 產品"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
深入瞭解 link:../learn/aws-storage.html["Amazon Web Services叢集的儲存類別"]。深入瞭解 link:../learn/azure-storage.html["適用於高效能叢集的儲存類別"]。深入瞭解 link:../learn/choose-class-and-size.html["GKE叢集的儲存類別"]。

+
.. 選擇*下一步*。
.. * 審查與核准 * ：檢閱組態詳細資料。
.. 選取 * 新增 * 將叢集新增至 Astra Control Service 。






== 變更預設儲存類別

您可以變更叢集的預設儲存類別。



=== 使用Astra Control變更預設儲存類別

您可以從Astra Control中變更叢集的預設儲存類別。如果叢集使用先前安裝的儲存後端服務、您可能無法使用此方法來變更預設儲存類別（*設為預設*動作無法選取）。在這種情況下、您可以 <<使用命令列變更預設儲存類別>>。

.步驟
. 在Astra Control Service UI中、選取* Clusters*。
. 在「*叢集*」頁面上、選取您要變更的叢集。
. 選擇* Storage*（儲存設備）選項卡。
. 選擇*儲存類別*類別。
. 針對您要設為預設的儲存類別、選取「*動作*」功能表。
. 選擇*設為預設*。




=== 使用命令列變更預設儲存類別

您可以使用Kubernetes命令變更叢集的預設儲存類別。無論叢集的組態為何、此方法都能正常運作。

.步驟
. 登入Kubernetes叢集。
. 列出叢集中的儲存類別：
+
[source, console]
----
kubectl get storageclass
----
. 從預設儲存類別中移除預設指定。以<SC_NAME> 儲存類別的名稱取代支援：
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. 將不同的儲存類別標示為預設。以<SC_NAME> 儲存類別的名稱取代支援：
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. 確認新的預設儲存類別：
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
