---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。 
---
= 從Astra Control Service開始管理Kubernetes叢集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。

* <<建立Kubernetes叢集>>
* <<開始管理Kubernetes叢集>>
* <<變更預設儲存類別>>




== 建立Kubernetes叢集

如果您還沒有叢集、可以建立符合的叢集 link:set-up-amazon-web-services.html#eks-cluster-requirements["Amazon Elastic Kubernetes服務（EKS）的Astra控制服務要求"]。如果您還沒有叢集、可以建立符合的叢集 link:set-up-google-cloud.html#gke-cluster-requirements["Google Kubernetes Engine（GKE）的Astra控制服務要求"]。如果您還沒有叢集、可以建立符合的叢集 link:set-up-microsoft-azure-with-anf.html#azure-kubernetes-service-cluster-requirements["Azure Kubernetes Service（含Azure NetApp Files ）的Astra Control Service要求"] 或 link:set-up-microsoft-azure-with-amd.html#azure-kubernetes-service-cluster-requirements["Azure Kubernetes Service（Astra Control Service）與Azure託管磁碟的相關要求"]。


NOTE: Astra Control Service支援使用Azure Active Directory（Azure AD）進行驗證與身分識別管理的高峰叢集。建立叢集時、請遵循中的指示 https://docs.microsoft.com/en-us/azure/aks/managed-aad["正式文件"^] 設定叢集使用Azure AD。您必須確保叢集符合高峰管理Azure AD整合的要求。

您可以上傳、將自我管理的叢集新增至Astra Control Service `kubeconfig.yaml` 檔案：您必須確保叢集符合中所述的要求 <<開始管理Kubernetes叢集>>。



== 開始管理Kubernetes叢集

登入Astra Control Service之後、您的第一步就是開始管理叢集。您可以新增由雲端供應商管理的叢集、或是自行管理的叢集。將叢集新增至Astra Control Service之前、您必須執行特定工作、並確保叢集符合特定需求。

.您的需求是什麼？#8217；需要由雲端供應商管理的叢集
[%collapsible]
====
ifdef::aws[]

.Amazon Web Services
* 您應該擁有Json檔案、其中包含建立叢集的IAM使用者認證。 link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["瞭解如何建立IAM使用者"]。
* Amazon FSX for NetApp ONTAP Sfa需要Astra Trident。如果您計畫將Amazon FSX for NetApp ONTAP 功能用作EKS叢集的儲存後端、請參閱中的Astra Trident資訊 link:set-up-amazon-web-services.html#eks-cluster-requirements["EKS叢集需求"]。
* （選用）如果您需要提供 `kubectl` 叢集的命令存取功能可讓其他不是叢集建立者的IAM使用者存取、請參閱中的指示 https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["如何在Amazon EKS中建立叢集後、提供其他IAM使用者和角色的存取權限？"^]。


endif::aws[]

ifdef::azure[]

.Microsoft Azure
* 建立服務主體時、您應該擁有包含Azure CLI輸出的Json檔案。 link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["瞭解如何設定服務主體"]。
+
如果您未將Azure訂閱ID新增至Json檔案、您也需要Azure訂閱ID。

* 如需私有的高效能叢集、請參閱 link:manage-private-cluster.html["從Astra Control Service管理私有叢集"^]。
* 如果您計畫將NetApp Cloud Volumes ONTAP 支援作為儲存後端、則需要設定Cloud Volumes ONTAP 支援功能以搭配Microsoft Azure使用。請參閱Cloud Volumes ONTAP 《The》 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["設定文件"^]。


endif::azure[]

ifdef::gcp[]

.Google Cloud
* 您應該擁有具有所需權限之服務帳戶的服務帳戶金鑰檔。 link:../get-started/set-up-google-cloud.html#create-a-service-account["瞭解如何設定服務帳戶"]。
* 如果您打算將NetApp Cloud Volumes ONTAP 支援作為儲存後端、則需要設定Cloud Volumes ONTAP 支援功能以搭配Google Cloud使用。請參閱Cloud Volumes ONTAP 《The》 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["設定文件"^]。


endif::gcp[]

====
.您的#8217；需要自行管理的叢集
[%collapsible]
====
您的自我管理叢集可以使用Astra Trident來與NetApp儲存服務建立連結、也可以使用Container Storage介面（Container Storage Interface、簡稱csi）驅動程式來與其他儲存服務建立連結。

Astra Control Service使用下列Kubernetes發佈版本來支援自我管理的叢集：

* Red Hat OpenShift Container Platform
* Rancher Kubernetes引擎
* 上游Kubernetes


您的自我管理叢集必須符合下列需求：

* 叢集必須可透過網際網路存取。
* 如果您使用或打算使用已啟用SCSI驅動程式的儲存設備、則叢集上必須安裝適當的SCSI驅動程式。如需使用SCSI驅動程式來整合儲存設備的詳細資訊、請參閱儲存服務的說明文件。
* 如果您使用或打算使用NetApp儲存設備、請確定您已安裝Astra Trident的版本 link:../get-started/requirements.html#operational-environment-requirements["由Astra Control Service支援"^]：
+

NOTE: 您可以 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["部署Astra Trident"^] 使用Trident運算子（手動或使用Helm圖表）或 `tridentctl`。在安裝或升級Astra Trident之前、請先檢閱 https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["支援的前端、後端及主機組態"^]。

+
** *已設定Trident儲存後端*：至少必須有一個Astra Trident儲存後端 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-postdeployment.html#step-1-create-a-backend["已設定"^] 在叢集上。
** *已設定Trident儲存類別*：至少必須有一個Astra Trident儲存類別 https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["已設定"^] 在叢集上。如果已設定預設儲存類別、請確定只有一個儲存類別具有該註釋。
** *已安裝並設定的Astra Trident Volume Snapshot控制器與Volume Snapshot類別*：Volume Snapshot控制器必須是 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["已安裝"^] 以便在Astra Control中建立快照。至少有一個Astra Trident `VolumeSnapshotClass` 過去了 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["設定"^] 由系統管理員執行。


* *可存取的Kubeconfig *：您可以存取 <<kubeconfig,叢集管理圖>> 這只包含一個內容元素。
* *僅限Rancher *：在Rancher環境中管理應用程式叢集時、請在Rancher提供的Kusbeconfig檔案中修改應用程式叢集的預設內容、以使用控制面內容而非Rancher API伺服器內容。如此可減少Rancher API伺服器的負載、並改善效能。


.（選用）檢查Astra Trident版本
如果叢集使用Astra Trident來提供儲存服務、請確定安裝的Astra Trident版本為最新版本。

.步驟
. 檢查Astra Trident版本。
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
如果安裝了Astra Trident、您會看到類似下列的輸出：

+
[listing]
----
NAME      VERSION
trident   22.10.0
----
+
如果未安裝Astra Trident、您會看到類似下列的輸出：

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
+

NOTE: 如果未安裝或不是最新的Astra Trident、而且您想要叢集使用Astra Trident來提供儲存服務、則必須先安裝最新版的Astra Trident、才能繼續進行。請參閱 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["Astra Trident文件"^] 以取得相關指示。

. 確保Pod正在執行：
+
[source, console]
----
kubectl get pods -n trident
----
. 檢查儲存類別是否使用支援的Astra Trident驅動程式。置備程式名稱應為 `csi.trident.netapp.io`。請參閱下列範例：
+
[source, console]
----
kubectl get sc
----
+
回應範例：

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----


.建立管理角色Kubeconfig（適用於執行Rancher、OpenShift和上游Kubernetes的叢集）
在執行步驟之前、請先確定機器上有下列項目：

* 已安裝KECV1.19或更新版本
* 具有作用中內容叢集管理權限的作用中Kbeconfig


.步驟
. 建立服務帳戶、如下所示：
+
.. 建立名為的服務帳戶檔案 `astracontrol-service-account.yaml`。
+
視需要調整名稱和命名空間。如果在此處進行變更、您應該在下列步驟中套用相同的變更。

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-service-account.yaml*
----
+
[source, yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astracontrol-service-account
  namespace: default
----
.. 套用服務帳戶：
+
[source, console]
----
kubectl apply -f astracontrol-service-account.yaml
----


. 授予叢集管理權限、如下所示：
+
.. 建立 `ClusterRoleBinding` 檔案已呼叫 `astracontrol-clusterrolebinding.yaml`。
+
視需要在建立服務帳戶時調整任何已修改的名稱和命名空間。

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-clusterrolebinding.yaml*
----
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astracontrol-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: astracontrol-service-account
  namespace: default
----
.. 套用叢集角色繫結：
+
[source, console]
----
kubectl apply -f astracontrol-clusterrolebinding.yaml
----


. 列出取代的服務帳戶機密 `<context>` 正確的安裝環境：
+
[source, console]
----
kubectl get serviceaccount astracontrol-service-account --context <context> --namespace default -o json
----
+
輸出的結尾應類似於下列內容：

+
[listing]
----
"secrets": [
{ "name": "astracontrol-service-account-dockercfg-vhz87"},
{ "name": "astracontrol-service-account-token-r59kr"}
]
----
+
中每個元素的索引 `secrets` 陣列開頭為0。在上述範例中、索引為 `astracontrol-service-account-dockercfg-vhz87` 將為0、索引則為 `astracontrol-service-account-token-r59kr` 應該是1。在輸出中、記下含有「權杖」一詞的服務帳戶名稱索引。

. 產生以下的Kbeconfig：
+
.. 建立 `create-kubeconfig.sh` 檔案：更換 `TOKEN_INDEX` 在下列指令碼開頭、使用正確的值。
+
[source, subs="specialcharacters,quotes"]
----
*create-kubeconfig.sh*
----
+
[source, console]
----
# Update these to match your environment.
# Replace TOKEN_INDEX with the correct value
# from the output in the previous step. If you
# didn't change anything else above, don't change
# anything else here.

SERVICE_ACCOUNT_NAME=astracontrol-service-account
NAMESPACE=default
NEW_CONTEXT=astracontrol
KUBECONFIG_FILE='kubeconfig-sa'

CONTEXT=$(kubectl config current-context)

SECRET_NAME=$(kubectl get serviceaccount ${SERVICE_ACCOUNT_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.secrets[TOKEN_INDEX].name}')
TOKEN_DATA=$(kubectl get secret ${SECRET_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.data.token}')

TOKEN=$(echo ${TOKEN_DATA} | base64 -d)

# Create dedicated kubeconfig
# Create a full copy
kubectl config view --raw > ${KUBECONFIG_FILE}.full.tmp

# Switch working context to correct context
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp config use-context ${CONTEXT}

# Minify
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp \
  config view --flatten --minify > ${KUBECONFIG_FILE}.tmp

# Rename context
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  rename-context ${CONTEXT} ${NEW_CONTEXT}

# Create token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-credentials ${CONTEXT}-${NAMESPACE}-token-user \
  --token ${TOKEN}

# Set context to use token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --user ${CONTEXT}-${NAMESPACE}-token-user

# Set context to correct namespace
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --namespace ${NAMESPACE}

# Flatten/minify kubeconfig
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  view --flatten --minify > ${KUBECONFIG_FILE}

# Remove tmp
rm ${KUBECONFIG_FILE}.full.tmp
rm ${KUBECONFIG_FILE}.tmp
----
.. 請輸入命令以將其套用至Kubernetes叢集。
+
[source, console]
----
source create-kubeconfig.sh
----


. （選用）將Kbeconfig重新命名為有意義的叢集名稱。保護您的叢集認證資料。
+
[listing]
----
chmod 700 create-kubeconfig.sh
mv kubeconfig-sa.txt YOUR_CLUSTER_NAME_kubeconfig
----


====
.步驟
. 在儀表板上、選取*管理Kubernetes叢集*。
+
依照提示新增叢集。

. *供應商*：選取您的雲端供應商、然後提供必要的認證資料以建立新的雲端執行個體、或選取要使用的現有雲端執行個體。


ifdef::aws[]

. * Amazon Web Services *：上傳Json檔案或從剪貼簿貼上Json檔案的內容、以提供Amazon Web Services IAM使用者帳戶的詳細資料。
+
Json檔案應包含建立叢集的IAM使用者認證。



endif::aws[]

ifdef::azure[]

. * Microsoft Azure *：上傳Json檔案或從剪貼簿貼上Json檔案的內容、以提供Azure服務主體的詳細資料。
+
當您建立服務主體時、Json檔案應包含Azure CLI的輸出。它也可以包含您的訂閱ID、以便自動新增至Astra。否則、您必須在提供Json之後手動輸入ID。



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform *：上傳檔案或從剪貼簿貼上內容、以提供服務帳戶金鑰檔案。
+
Astra Control Service使用服務帳戶來探索在Google Kubernetes Engine中執行的叢集。



endif::gcp[]

. *其他*：上傳以提供自我管理叢集的詳細資料 `kubeconfig.yaml` 檔案或貼上的內容 `kubeconfig.yaml` 檔案。
+

NOTE: 如果您自行建立 `kubeconfig` 檔案中、您應該只定義*一個*內容元素。請參閱 https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Kubernetes文件"^] 以取得有關建立的資訊 `kubeconfig` 檔案：

+
.. * Cloud instance name*（適用於供應商管理的叢集）：為新增此叢集時所建立的新雲端執行個體提供名稱。深入瞭解 link:../use/manage-cloud-instances.html["雲端執行個體"]。
+

NOTE: 從叢集清單中選取時、請小心注意「合格」索引標籤。如果出現警告、請將游標暫留在警告上、以判斷叢集是否有問題。例如、它可能會識別叢集沒有工作節點。





ifdef::azure[]

+


NOTE: 如果您選取標記有「私有」圖示的叢集、則會使用私有IP位址、而Astra Control則需要Astra Connector來管理叢集。如果您看到一則訊息、指出您需要安裝Astra Connector、 link:manage-private-cluster.html["請參閱這些指示"] 安裝Astra Connector並啟用叢集管理。安裝Astra Connector之後、叢集應該符合資格、您可以繼續新增叢集。

endif::azure[]

. *認證名稱*（適用於自我管理的叢集）：提供您要上傳至Astra Control的自我管理叢集認證名稱。根據預設、認證名稱會自動填入為叢集名稱。
. （選用）* Storage *：選取要將Kubernetes應用程式部署至此叢集的儲存類別、預設為使用。
+
[NOTE]
====
每個雲端供應商的儲存服務都會顯示下列價格、效能和恢復能力資訊：

ifdef::gcp[]

** 適用於Google Cloud的解決方案：價格、效能和恢復能力資訊Cloud Volumes Service
** Google持續磁碟：沒有可用的價格、效能或恢復能力資訊


endif::gcp[]

ifdef::azure[]

** 支援：效能與恢復能力資訊Azure NetApp Files
** Azure託管磁碟：不提供價格、效能或恢復能力資訊


endif::azure[]

ifdef::aws[]

** Amazon Elastic Block Store：沒有可用的價格、效能或恢復能力資訊
** Amazon FSX for NetApp ONTAP 不提供價格、效能或恢復能力資訊


endif::aws[]

** NetApp Cloud Volumes ONTAP 產品：不提供價格、效能或恢復能力資訊


====
+
每個儲存類別都可以使用下列其中一項服務：



ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]
* https://cloud.google.com/persistent-disk/["Google持續磁碟"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure託管磁碟"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon彈性區塊存放區"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 產品"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
深入瞭解 link:../learn/aws-storage.html["Amazon Web Services叢集的儲存類別"]。深入瞭解 link:../learn/azure-storage.html["適用於高效能叢集的儲存類別"]。深入瞭解 link:../learn/choose-class-and-size.html["GKE叢集的儲存類別"]。

+
.. *審查與核准*：檢閱組態詳細資料、然後選取*新增叢集*。




.結果
*對於供應商管理的叢集*：如果這是您為此雲端供應商新增的第一個叢集、Astra Control Service會為雲端供應商建立物件存放區、以便備份在合格叢集上執行的應用程式。（當您新增此雲端供應商的後續叢集時、不會再建立其他物件存放區。）如果您指定預設儲存類別、Astra Control Service會設定您指定的預設儲存類別。對於在Amazon Web Services或Google Cloud Platform中管理的叢集、Astra Control Service也會在叢集上建立管理員帳戶。這些動作可能需要幾分鐘的時間。



== 變更預設儲存類別

您可以變更叢集的預設儲存類別。



=== 使用Astra Control變更預設儲存類別

您可以從Astra Control中變更叢集的預設儲存類別。如果叢集使用先前安裝的儲存後端服務、您可能無法使用此方法來變更預設儲存類別（*設為預設*動作無法選取）。在這種情況下、您可以 <<使用命令列變更預設儲存類別>>。

.步驟
. 在Astra Control Service UI中、選取* Clusters*。
. 在「*叢集*」頁面上、選取您要變更的叢集。
. 選擇* Storage*（儲存設備）選項卡。
. 選擇*儲存類別*類別。
. 針對您要設為預設的儲存類別、選取「*動作*」功能表。
. 選擇*設為預設*。




=== 使用命令列變更預設儲存類別

您可以使用Kubernetes命令變更叢集的預設儲存類別。無論叢集的組態為何、此方法都能正常運作。

.步驟
. 登入Kubernetes叢集。
. 列出叢集中的儲存類別：
+
[source, console]
----
kubectl get storageclass
----
. 從預設儲存類別中移除預設指定。以<SC_NAME> 儲存類別的名稱取代支援：
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. 將不同的儲存類別標示為預設。以<SC_NAME> 儲存類別的名稱取代支援：
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. 確認新的預設儲存類別：
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]



== 以取得更多資訊

* link:manage-private-cluster.html["管理私有叢集"]


endif::azure[]
