---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。 
---
= 從Astra Control Service開始管理Kubernetes叢集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。

*  a Kubernetes cluster
*  managing Kubernetes clusters


ifdef::azure[]

*  a private cluster


endif::azure[]

ifdef::aws[]

*  cluster access to other users


endif::aws[]

*  the default storage class




== 建立Kubernetes叢集

如果您還沒有叢集、請建立符合的叢集 link:set-up-amazon-web-services.html#eks-cluster-requirements["Amazon Elastic Kubernetes服務（EKS）的Astra控制服務要求"]。如果您還沒有叢集、請建立符合的叢集 link:set-up-google-cloud.html#gke-cluster-requirements["Google Kubernetes Engine（GKE）的Astra控制服務要求"]。如果您還沒有叢集、請建立符合的叢集 link:set-up-microsoft-azure-with-anf.html["Azure Kubernetes Service（含Azure NetApp Files ）的Astra Control Service要求"] 或 link:set-up-microsoft-azure-with-amd.html["Azure Kubernetes Service（Astra Control Service）與Azure託管磁碟的相關要求"]。


NOTE: Astra Control Service支援使用Azure Active Directory（Azure AD）進行驗證與身分識別管理的高峰叢集。建立叢集時、請遵循中的指示 https://docs.microsoft.com/en-us/azure/aks/managed-aad["正式文件"^] 設定叢集使用Azure AD。您必須確保叢集符合高峰管理Azure AD整合的要求。



== 開始管理Kubernetes叢集

登入Astra Control Service之後、您的第一步就是開始管理叢集。

如果在新增叢集時、叢集上未設定Volume Snapshot類別、Astra Control Service會嘗試安裝具有預設組態的類別。

[NOTE]
====
當Astra Control管理叢集時、它會追蹤叢集的預設儲存類別。如果您使用「kubecll」命令變更儲存類別、Astra Control會還原變更。若要變更由Astra Control管理之叢集中的預設儲存類別、請使用下列其中一種方法：

* 使用Astra Control API「PUT /managedClusters'端點」、並使用「DefaultStorageClass」參數指派不同的預設儲存類別。
* 使用Astra Control Web UI指派不同的預設儲存類別。請參閱  the default storage class。


====
ifdef::aws[]

* 對於Amazon Web Services、您應該擁有Json檔案、其中包含建立叢集的IAM使用者的認證資料。 link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["瞭解如何建立IAM使用者"]。
* Amazon FSX for NetApp ONTAP Sfa需要Astra Trident。如果您計畫將Amazon FSX for NetApp ONTAP 功能用作EKS叢集的儲存後端、請確定您已完成 link:set-up-amazon-web-services.html#optional-configure-astra-trident-for-amazon-fsx-for-netapp-ontap["步驟7"] 的設定說明。


endif::aws[]

ifdef::gcp[]

* 若為GKE、您應該擁有具有所需權限之服務帳戶的服務帳戶金鑰檔案。 link:../get-started/set-up-google-cloud.html#create-a-service-account["瞭解如何設定服務帳戶"]。


endif::gcp[]

ifdef::azure[]

* 若為高效能、您應該擁有Json檔案、其中應包含建立服務主體時Azure CLI的輸出。 link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["瞭解如何設定服務主體"]。
+
如果您未將Azure訂閱ID新增至Json檔案、您也需要Azure訂閱ID。

* 若為私有高層叢集：
+
** 叢集應符合中所述的需求 https://docs.microsoft.com/en-us/azure/aks/private-clusters["Azure文件"^]。
** 您需要在Astra服務叢集上安裝Astra Connector、以便Astra Control Service能夠管理叢集。若要安裝Astra Connector、  a private cluster,請遵循下列指示。




endif::azure[]

.步驟
. 在儀表板上、選取*管理Kubernetes叢集*。
+
依照提示新增叢集。

. *供應商*：選取您的雲端供應商、然後提供必要的認證資料。


ifdef::aws[]

. * Amazon Web Services *：上傳Json檔案或從剪貼簿貼上Json檔案的內容、以提供Amazon Web Services IAM使用者帳戶的詳細資料。
+
Json檔案應包含建立叢集的IAM使用者認證。



endif::aws[]

ifdef::azure[]

. * Microsoft Azure *：上傳Json檔案或從剪貼簿貼上Json檔案的內容、以提供Azure服務主體的詳細資料。
+
當您建立服務主體時、Json檔案應包含Azure CLI的輸出。它也可以包含您的訂閱ID、以便自動新增至Astra。否則、您必須在提供Json之後手動輸入ID。



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform *：上傳檔案或從剪貼簿貼上內容、以提供服務帳戶金鑰檔案。
+
Astra Control Service使用服務帳戶來探索在Google Kubernetes Engine中執行的叢集。



endif::gcp[]

. *叢集*：選取您要新增的叢集。
+
請謹慎注意「合格」標籤。如果出現警告、請將游標暫留在警告上、以判斷叢集是否有問題。例如、它可能會識別叢集沒有工作節點。

+
如果您選取的叢集尚未設定Cloud Volumes Service 成適用於Google Cloud的功能、則會出現警告。此叢集未安裝及設定NetApp Trident。如果您打算使用不同的儲存服務、可以繼續新增叢集。

+
請謹慎注意「合格」標籤。如果出現警告、請將游標暫留在警告上、以判斷叢集是否有問題。例如、它可能會識別叢集沒有工作節點。

+
如果您選取的叢集尚未針對Amazon Web Services進行設定、則會出現警告。此叢集未安裝及設定NetApp Trident。如果您打算使用不同的儲存服務、可以繼續新增叢集。

+
請謹慎注意「合格」標籤。如果出現警告、請將游標暫留在警告上、以判斷叢集是否有問題。例如、它可能會識別叢集沒有工作節點。

+
如果您選取的叢集尚未設定Azure NetApp Files 成供使用、則會出現警告。此叢集未安裝及設定NetApp Trident。如果您打算使用不同的儲存服務、可以繼續新增叢集。

+
如果您選取標記有「私有」圖示的叢集、則會使用私有IP位址、而Astra Control則需要Astra Connector來管理叢集。如果您看到一則訊息、指出您需要安裝Astra Connector、  a private cluster,請遵循下列指示 安裝Astra Connector並啟用叢集管理。安裝Astra Connector之後、叢集應該符合資格、您可以繼續新增叢集。

. *儲存設備*：選取要將Kubernetes應用程式部署至此叢集的儲存類別、以供預設使用。
+
[NOTE]
====
每個雲端供應商的儲存服務都會顯示下列價格、效能和恢復能力資訊：

ifdef::gcp[]

** 適用於Google Cloud的解決方案：價格、效能和恢復能力資訊Cloud Volumes Service
** Google持續磁碟：沒有可用的價格、效能或恢復能力資訊


endif::gcp[]

ifdef::azure[]

** 支援：效能與恢復能力資訊Azure NetApp Files
** Azure託管磁碟：不提供價格、效能或恢復能力資訊


endif::azure[]

ifdef::aws[]

** Amazon Elastic Block Store：沒有可用的價格、效能或恢復能力資訊
** Amazon FSX for NetApp ONTAP 不提供價格、效能或恢復能力資訊


endif::aws[]

====
+
每個儲存類別都可以使用下列其中一項服務：



ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]
* https://cloud.google.com/persistent-disk/["Google持續磁碟"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure託管磁碟"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon彈性區塊存放區"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 產品"^]


endif::aws[]

+深入瞭解 link:../learn/aws-storage.html["Amazon Web Services叢集的儲存類別"]。深入瞭解 link:../learn/azure-storage.html["適用於高效能叢集的儲存類別"]。深入瞭解 link:../learn/choose-class-and-size.html["GKE叢集的儲存類別"]。

. *審查與核准*：檢閱組態詳細資料、然後選取*新增叢集*。


Astra Control Service會在合格的叢集上建立物件存放區以供應用程式備份、在叢集上建立管理員帳戶、並設定您指定的預設儲存類別。此程序可能需要5分鐘的時間。

ifdef::azure[]



== 管理私有叢集

您可以使用Astra Control Service來管理私有的高可用性叢集。若要這麼做、您必須在私有的Astra服務叢集上安裝Astra Connector運算子。您可以在新增叢集以進行管理之前、或在系統提示時新增叢集的過程中完成此步驟。

.步驟
. 為Astra Connector運算子建立命名空間。
+
[listing]
----
kubectl create ns astra-connector-operator
----
. 將「astraconnecor_toper.yaml」檔案套用到運算子命名空間。
+
[listing]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 為私有叢集元件建立命名空間。
+
[listing]
----
kubectl create ns astra-connector
----
. 套用Astra Connector自訂資源定義（CRD）。
+
[listing]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. 檢查Astra Connector的狀態。
+
[listing]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
您應該會看到類似下列的輸出：

+
[listing]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----


endif::azure[]

ifdef::aws[]



== 為其他使用者提供叢集存取

您可以選擇性地將叢集的「kubecl」命令存取權提供給不是叢集建立者的其他IAM使用者。

如需相關指示、請參閱 https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["如何在Amazon EKS中建立叢集後、提供其他IAM使用者和角色的存取權限？"^]。

endif::aws[]



== 變更預設儲存類別

您可以變更叢集的預設儲存類別。

.步驟
. 在Astra Control Service UI中、選取* Clusters*。
. 在「*叢集*」頁面上、選取您要變更的叢集。
. 選擇* Storage*（儲存設備）選項卡。
. 選擇*儲存類別*類別。
. 針對您要設為預設的儲存類別、選取「*動作*」功能表。
. 選擇*設為預設*。

