---
sidebar: sidebar 
permalink: get-started/check-astra-trident-version.html 
keywords: astra trident, check, version, astra control provisioner 
summary: 對於自行管理的叢集、您可能需要確定使用的是正確的 Astra Trident 版本。 
---
= 檢查 Astra Trident 版本
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
若要新增使用 Astra Control Provisioner 或 Astra Trident 進行儲存服務的自我管理叢集、請確定 Astra Trident 的安裝版本為 23.10 或最新版本。

.步驟
. 判斷您正在執行的 Astra Trident 版本：
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
如果安裝了Astra Trident、您會看到類似下列的輸出：

+
[listing]
----
NAME      VERSION
trident   24.02.0
----
+
如果未安裝Astra Trident、您會看到類似下列的輸出：

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
. 執行下列其中一項：
+
** 如果您執行的是 Astra Trident 23.01 或更早版本、請使用這些項目 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html["說明"^] 在升級至 Astra Control Provisioner 之前、先升級至較新版本的 Astra Trident 。您可以 link:../use/enable-acp.html["執行直接升級"] 如果您的 Astra Trident 位於 24.02 版的四個版本視窗內、則為 Astra Control Provisioner 24.02 。例如、您可以直接從 Astra Trident 23.04 升級至 Astra Control Provisioner 24.02 。
** 如果您執行的是 Astra Trident 23.10 或更新版本、請確認 Astra Control Provisioner 已完成 link:../use/faq.html#running-acp-check["已啟用"]。Astra Control Provisioner 無法搭配 23.10 之前的 Astra Control Center 版本使用。 link:../get-started/enable-acp.html["升級 Astra Control Provisioner"] 因此它與您要升級以存取最新功能的 Astra Control Center 版本相同。


. 確保Pod正在執行：
+
[source, console]
----
kubectl get pods -n trident
----
. 檢查儲存類別是否使用支援的Astra Trident驅動程式。置備程式名稱應為 `csi.trident.netapp.io`。請參閱下列範例：
+
[source, console]
----
kubectl get sc
----
+
回應範例：

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----

