---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: faq, frequently asked questions 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= Astra Control Service的常見問題集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 總覽

Astra Control旨在簡化Kubernetes原生應用程式的應用程式資料生命週期管理作業。Astra Control Service支援在多個雲端供應商環境中執行的Kubernetes叢集。

以下各節提供使用Astra Control時可能會遇到的其他問題解答。如需進一步的說明、請聯絡astra.feedback@netapp.com



== 使用Astra Control

*註冊Astra Control時為何需要提供這麼多詳細資料？*

Astra Control在註冊時需要準確的客戶資訊。這項資訊必須經過全球貿易法規遵循（GTC）檢查。

*註冊Astra Control時為什麼收到「登錄失敗」錯誤？*

Astra Control要求您在就職部分提供準確的客戶資訊。如果您提供的資訊不正確、您將會收到「Registration Failed（註冊失敗）」錯誤訊息。您所屬的其他帳戶也會遭到鎖定。

*什麼是Astra Control Service URL？*

您可以在存取Astra Control Service https://astra.netapp.io[]。

*我寄了一封電子郵件邀請函給同事、但他們尚未收到。我該怎麼辦？*

請他們查看垃圾郵件資料夾中是否有來自do-not-reply@netapp.com的電子郵件、或在收件匣中搜尋「邀請」。 您也可以移除使用者並嘗試重新新增。

*我從免費方案升級至優質PayGO方案。前10個應用程式的費用是否會扣除？*

是的。在升級至優質方案之後、Astra Control會開始為您帳戶中的所有託管應用程式收取費用。

*我在一個月內升級至Premium PayGO方案。我會收取整個月的費用嗎？*

否、從您升級至優質方案開始計費。

*我正在使用免費方案、我是否會收到持續大量報銷的費用？*

是的、您將會從雲端供應商收取叢集所使用的「持續磁碟區」費用。



== 正在登錄Kubernetes叢集

*在將叢集新增至Astra Control Service之前、我是否需要在叢集上安裝SCSI驅動程式？*

不可以當您的叢集新增至Astra Control時、該服務會自動在Kubernetes叢集上安裝NetApp的Trident Container Storage Interface（SCSI）驅動程式。此驅動程式可用於為雲端供應商所支援的叢集配置持續磁碟區。

*新增Astra Control Service之後、我需要將工作節點新增至叢集。我該怎麼辦？*

新的工作節點可新增至現有資源池、或只要是Ubuntu映像類型、就能建立新資源池。Astra Control會自動探索這些功能。如果在Astra Control中看不到新節點、請檢查新的工作節點是否執行支援的映像類型。您也可以使用「kubectl Get nodes」命令來驗證新工作節點的健全狀況。

ifdef::azure[]



== 登錄高效能叢集

*我可以將私有的高層叢集新增至Astra Control Service嗎？*

是的、您可以將私有的高層叢集新增至Astra Control Service。若要新增私有的高效能叢集、請參閱 link:add-first-cluster.html["從Astra Control Service開始管理Kubernetes叢集"]。

*我可以使用Active Directory來管理高效能叢集的驗證嗎？*

是的、您可以將您的高效能叢集設定為使用Azure Active Directory（Azure AD）進行驗證和身分識別管理。建立叢集時、請遵循中的指示 https://docs.microsoft.com/en-us/azure/aks/managed-aad["正式文件"^] 設定叢集使用Azure AD。您必須確保叢集符合高峰管理Azure AD整合的要求。

endif::azure[]

ifdef::gcp[]



== 正在登錄GKE叢集

*我可以將私有GKE叢集新增至Astra Control Service嗎？*

是的、您可以將私有GKE叢集新增至Astra Control Service。若要建立Google Kubernetes Engine（GKE）私有叢集、 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Project_Astra/How_to_create_a_private_GKE_cluster_to_work_with_project_Astra["請依照此知識庫文章中的指示操作"^]。

私有叢集必須具有 https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["授權網路"^] 設定為允許Astra控制IP位址：

52.188.218.166/32

*我的GKE叢集是否可以位於共用VPC上？*

是的、Astra Control可以管理位於共享VPC中的叢集。 link:set-up-google-cloud.html["瞭解如何設定Astra服務帳戶以進行共用VPC組態"]。

*何處可以找到GCP上的服務帳戶認證資料？*

登入之後 https://console.cloud.google.com/["Google Cloud Console"^]、您的服務帳戶詳細資料將會顯示在「* IAM and admin*」區段中。如需詳細資料、請參閱 link:set-up-google-cloud.html["如何設定Google Cloud for Astra Control"]。

*我想新增不同GCP專案的GKE叢集。Astra Control是否支援此功能？*

否、這不是支援的組態。僅支援單一GCP專案。

endif::gcp[]



== 移除叢集

*如何正確取消註冊、關閉叢集及刪除相關的磁碟區？*

. link:../use/unmanage.html["從Astra Control取消應用程式管理"]。
. link:../use/unmanage.html#stop-managing-compute["從Astra Control取消登錄叢集"]。
. link:../use/unmanage.html#deleting-clusters-from-your-cloud-provider["刪除持續的Volume宣告"]。
. 刪除叢集。


*從Astra Control移除叢集之後、應用程式和資料會發生什麼變化？*

從Astra Control移除叢集不會對叢集的組態（應用程式和持續儲存）進行任何變更。在該叢集上執行的任何Astra Control快照或應用程式備份都無法還原。儲存在儲存後端內的Volume Snapshot資料將不會移除。由Astra Control所建立的持續儲存備份仍會保留在雲端供應商的物件存放區內、但無法還原。

ifdef::gcp[]


WARNING: 透過GCP刪除叢集之前、請務必先從Astra Control移除叢集。在GCP中刪除叢集時、如果叢集仍由Astra Control進行管理、可能會對Astra Control帳戶造成問題。

endif::gcp[]

*從Astra Control移除叢集時、是否會解除安裝Astra Trident？*

從Astra Control移除Astra Trident時、不會從叢集解除安裝Astra Trident。



== 管理應用程式

* Astra Control是否能部署應用程式？*

Astra Control不會部署應用程式。應用程式必須部署在Astra Control之外。

*「探索到的應用程式」清單中未顯示「我的應用程式」。我可以檢查哪些項目來識別問題？*

當*探索應用程式*中未列出應用程式時、請執行「kubectl Get pod -A | grep [pod name]」來檢查Kubernetes pod的狀態和健全狀況。如果Pod正常運作、請檢查應用程式是否列在*忽略應用程式*之下。

* Astra Control能否管理非NetApp儲存設備上的應用程式？*

不可以雖然Astra Control可以探索使用非NetApp儲存設備的應用程式、但它無法管理使用非NetApp儲存設備的應用程式。

ifdef::gcp[]

*我看不到任何應用程式的PVCS都綁定到GCP CVS。錯誤為何？*

Astra Trident操作員成功新增至Astra Control之後、將預設儲存類別設為「NetApp-CVs-perf-perf-pPremium」。當應用程式的PVCS不受限於Cloud Volumes Service Google Cloud的功能時、您可以採取幾個步驟：

* 執行「kubectl Get SC」、然後檢查預設的儲存類別。
* 檢查用於部署應用程式的yaml檔案或Helm圖表、查看是否定義了不同的儲存類別。
* 請檢查以確定工作節點映像類型為Ubuntu、且NFS掛載成功。


endif::gcp[]

*停止從Astra Control管理應用程式之後、應用程式會發生什麼事？*

將刪除任何現有的備份或快照。應用程式與資料仍可繼續使用。資料管理作業無法用於未受管理的應用程式、或屬於它的任何備份或快照。



== 資料管理作業

* Astra Control在何處建立物件存放區？*

第一個託管叢集的地理區域決定物件存放區的位置。例如、如果您新增的第一個叢集位於歐洲區域、則會在該地理區域中建立該儲存區。如有需要、您可以 link:../use/manage-buckets.html["新增額外的貯體"]。

*我的帳戶中有我沒有建立的快照。他們來自何處？*

在某些情況下、Astra Control會自動建立快照、做為執行其他程序的一部分。如果快照時間超過幾分鐘、您可以安全地刪除快照。

*我的應用程式使用數個PV。Astra Control是否會對所有這些PVCs執行快照和備份？*

是的。Astra Control在應用程式上執行的快照作業包括繫結至應用程式PVCS的所有PV快照。

*我可以直接透過雲端供應商來管理Astra Control拍攝的快照嗎？*

不可以Astra Control所拍攝的快照與備份、只能透過Astra Control進行管理。
