---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 設定環境之後、您就可以建立Kubernetes叢集、然後將其新增至Astra Control Service。 
---
= 從Astra Control Service管理私有叢集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
您可以使用 Astra Control Service 來管理私有 Azure Kubernetes Service （ Astra Control Service ）叢集、以及在 AKS 中管理私有 Red Hat OpenShift 叢集。這些指示假設您已建立私有 aks 或 OpenShift 叢集、並準備了安全的方法來遠端存取；如需建立及存取私有 aks 或 OpenShift 叢集的詳細資訊、請參閱下列文件：

* https://docs.microsoft.com/azure/aks/private-clusters["適用於私有 aks 叢集的 Azure 文件"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["適用於私有 OpenShift 叢集的 Azure 文件"^]




== 安裝Astra Connector運算子

您需要在私有叢集上安裝 Astra Connector 運算子。如果您使用的是堡壘主機、請從堡壘主機的命令列發出這些命令。

.步驟
. 複製Astra Connector運算子GitHub儲存庫：
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. 將目錄變更為解壓縮的運算子套件的最上層、以便使用「ls」命令查看「astraconnecor_opiler.yaml」檔案。
. 為Astra Connector運算子建立命名空間。
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. 將「astraconnecor_toper.yaml」檔案套用到運算子命名空間。
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 為私有叢集元件建立命名空間。
+
[source, console]
----
kubectl create ns astra-connector
----
. 使用中的指示產生Astra Control API權杖 https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Astra Automation文件"^]。
. 修改 Astra Connector 運算子儲存庫組態 / 範例目錄中的範例組態檔案、以納入 `spec.natssync-client.cloud-bridge-url` 金鑰。例如：
+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----
. 套用Astra Connector自訂資源定義（CRD）。
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. 檢查Astra Connector的狀態。
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
您應該參考類似下列的輸出：

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== 設定持續儲存

設定叢集的持續儲存設備。您可以使用Azure NetApp Files 由NetApp或Azure管理的磁碟。如需使用下列選項設定Azure的詳細資訊、請參閱入門文件：

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html["使用Azure NetApp Files 更新功能來設定Microsoft Azure"]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["使用Azure託管磁碟來設定Microsoft Azure"]




== 將私有叢集新增至Astra Control Service

您現在可以將私有叢集新增至 Astra Control Service 。遵循標準工作流程、將叢集新增至Astra Control Service： https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["從Astra Control Service開始管理Kubernetes叢集"]。
