---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: Astra Control Service 整合在 NetApp BlueXP 的驗證服務中。註冊 BlueXP 、即可存取 Astra Control Service 和 NetApp 的其他雲端服務。 
---
= 註冊Astra Control Service帳戶
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
若要使用 Astra Control Service 、您需要與 NetApp BlueXP 帳戶相關聯的 Astra Control Service 帳戶。完成 Astra Control Service 註冊程序、如果您尚未擁有 BlueXP 帳戶、請註冊 BlueXP 以存取 Astra Control Service 。



== 註冊Astra Control帳戶

登入Astra Control Service之前、您必須先完成註冊程序、才能取得Astra Control Service帳戶。

當您使用Astra Control Service時、您將從帳戶中管理應用程式。帳戶包括可檢視及管理帳戶內應用程式的使用者、以及您的帳單詳細資料。

.步驟
. https://cloud.netapp.com/astra["前往 BlueXP 上的 Astra Control 頁面"^]。
. 選擇 * 立即開始 * 。
. 在表單中提供必要資訊。
+
填寫表單時請注意以下幾點重要事項：

+
** 您的公司名稱和地址必須準確無誤、因為我們會驗證這些名稱和地址、以符合全球貿易法規遵循的要求。
** 「* Astra帳戶名稱*」是貴企業的Astra Control Service帳戶名稱。您會在Astra Control Service使用者介面中看到此名稱。請注意、您可以視需要建立其他帳戶（最多5個）。
** 在 * 商務電子郵件地址 * 欄位中、如果您有 NetApp BlueXP 帳戶、請在此輸入您用於該帳戶的電子郵件。如果您還沒有 NetApp BlueXP 帳戶、請在註冊 BlueXP 時使用您在此輸入的電子郵件地址。


. 選擇*建立帳戶*。




== 註冊BlueXP

Astra Control Service 整合在 NetApp BlueXP 的驗證服務中。您可以使用 BlueXP 或 NetApp 支援網站 認證登入 NetApp BlueXP 。如果您尚未擁有 NetApp BlueXP 或 NetApp 支援網站 帳戶、請註冊 BlueXP 、以便存取 Astra Control Service 和 NetApp 的其他雲端服務。如果您已經擁有 BlueXP 或 NetApp 支援網站 帳戶、並且已完成註冊、則可以存取 https://astra.netapp.io["Astra控制服務"^] 直接使用 BlueXP 或 NetApp 支援網站 認證。


TIP: 您也可以使用公司目錄（同盟身分識別）的認證、使用單一登入來登入 BlueXP 。若要深入瞭解、請前往 https://cloud.netapp.com/help-center["說明中心"^] 然後選取* Cloud Central登入選項*。

.步驟
. 前往 https://cloud.netapp.com["NetApp BlueXP"^]。
. 在右上角、選取 * 開始使用 * 。
. 選擇*註冊*。
. 填寫表單。
+
請確定您在此輸入的電話號碼和電子郵件地址與您在前一張 Astra Control 註冊表單中使用的相同。

. 選擇*註冊*。
+

TIP: 您在這些表單中輸入的電子郵件地址適用於您的 NetApp BlueXP 使用者 ID 。當您註冊新的 Astra Control 帳戶、或 Astra Control 管理員邀請您使用現有的 Astra Control 帳戶時、請使用此 BlueXP 使用者 ID 。

. 等待 NetApp BlueXP 的電子郵件。電子郵件來自saas.support@netapp.com的地址、可能需要數分鐘才能送達。請務必檢查您的垃圾郵件資料夾。
. 當電子郵件送達時、請選取電子郵件中的連結以驗證您的電子郵件地址。


.結果
您現在可以登入 Active BlueXP 使用者。

註冊之後、您可以直接從存取 Astra Control https://astra.netapp.io[]。
