---
sidebar: sidebar 
permalink: get-started/videos.html 
keywords: videos, Astra Control Service videos 
summary: 本文件網站上的許多頁面都包含影片、說明如何使用Astra Control Service完成工作。如果您只對影片感興趣、我們會在單一頁面上收集所有影片（例如播放清單）、讓您更輕鬆。 
---
= Astra Control Service影片
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本文件網站上的許多頁面都包含影片、說明如何完成Astra Control Service的工作。如果您只對影片感興趣、我們會在單一頁面上收集所有影片（例如播放清單）、讓您輕鬆完成這項工作。

ifdef::gcp[]



== 設定Google Cloud的影片

以下影片說明如何在Google Cloud中完成設定需求、然後才能探索在GCP中執行的Kubernetes叢集。



=== 啟用API

您的專案需要存取特定Google Cloud API的權限。下列影片說明如何從Google Cloud主控台啟用API。 link:set-up-google-cloud.html#enable-apis-in-your-project["深入瞭解如何啟用API"]。

video::get-started/video-enable-gcp-apis.mp4[width=848,height=480]


=== 建立服務帳戶

Astra Control Service使用Google Cloud服務帳戶、代表您協助Kubernetes應用程式資料管理。下列影片說明如何從Google Cloud主控台建立服務帳戶。 link:set-up-google-cloud.html#create-a-service-account["深入瞭解如何建立服務帳戶"]。

video::get-started/video-create-gcp-service-account.mp4[width=848,height=480]


=== 建立服務帳戶金鑰

Astra Control Service使用服務帳戶金鑰來建立您剛設定的服務帳戶身分。下列影片說明如何從Google Cloud主控台建立服務帳戶金鑰。 link:set-up-google-cloud.html#create-a-service-account-key-2["深入瞭解如何建立服務帳戶金鑰"]。

video::get-started/video-create-gcp-service-account-key.mp4[width=848,height=480]
endif::gcp[]



== 使用Astra Control的影片

下列影片說明如何使用Astra Control完成一般工作。



=== 從Astra Control管理叢集

登入Astra Control Service之後、您的第一步是新增Kubernetes運算。 link:add-first-cluster.html["深入瞭解叢集管理"]。

video::get-started/video-manage-cluster.mp4[width=848,height=480]


=== 設定保護原則

保護原則可在已定義的排程中建立快照、備份或兩者、以保護應用程式。您可以選擇每小時、每天、每週和每月建立快照和備份、也可以指定要保留的複本數量。 link:../use/protect-apps.html["深入瞭解如何設定保護原則"]。

video::use/video-set-protection-policy.mp4[width=848,height=480]