---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 已知問題可識別可能導致您無法成功使用本產品版本的問題。 
---
= 已知問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知問題可識別可能導致您無法成功使用本產品版本的問題。

下列已知問題會影響目前的版本：

.應用程式
* <<無法在已刪除和重新建立的命名空間上定義應用程式>>


.備份、還原及複製
* <<使用特定版本的PostgreSQL時、應用程式複製失敗>>
* <<如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗>>
* <<ONTAP NAS 經濟型儲存類別的就地還原作業失敗>>
* <<使用 Kerberos 進行中加密時、從備份還原可能會失敗>>
* <<刪除保留原則過期的貯體後、備份資料仍保留在貯體中>>


.其他問題
* <<當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗>>




== 無法在已刪除和重新建立的命名空間上定義應用程式

如果您使用命名空間定義應用程式、刪除命名空間、然後將應用程式重新安裝到同一個命名空間、則作業會失敗並顯示錯誤代碼為409。若要使用重新建立的命名空間定義應用程式、請先刪除舊的應用程式執行個體。



== 使用特定版本的PostgreSQL時、應用程式複製失敗

同一個叢集內的應用程式複製作業、會持續失敗、並顯示Bitnami PostgreSQL 11.5.0圖表。若要成功複製、請使用舊版或更新版本的圖表。



== 如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗

在此案例中、備份與快照會失敗、並顯示UI 500錯誤。因應措施是重新整理應用程式清單。



== ONTAP NAS 經濟型儲存類別的就地還原作業失敗

如果您執行應用程式的就地還原（將應用程式還原至其原始命名空間）、應用程式的儲存類別會使用 `ontap-nas-economy` 驅動程式、如果未隱藏快照目錄、還原作業可能會失敗。在就地還原之前、請遵循中的指示 link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["啟用 ONTAP NAS 經濟營運的備份與還原"^] 可隱藏 Snapshot 目錄。



== 使用 Kerberos 進行中加密時、從備份還原可能會失敗

當您將應用程式從備份還原至使用 Kerberos 進行中加密的儲存後端時、還原作業可能會失敗。此問題不會影響從快照還原或使用 NetApp SnapMirror 複寫應用程式資料。


NOTE: 在 NFSv4 磁碟區時使用 Kerberos 進行中加密時、請確定 NFSv4 磁碟區使用的是正確的設定。請參閱的「 NetApp NFSv4 網域組態」一節（第 13 頁） https://www.netapp.com/media/16398-tr-3580.pdf["NetApp NFSv4 增強與最佳實務指南"^]。



== 刪除保留原則過期的貯體後、備份資料仍保留在貯體中

如果您在貯體保留原則過期後刪除應用程式的不可變備份、則備份會從 Astra Control 刪除、但不會從貯體中刪除。因應措施是、如果您需要刪除應用程式的最新備份或所有備份、請從儲存後端手動移除備份。


NOTE: 如果應用程式有多個備份、請移除最新的備份或應用程式的所有備份。如果您移除任何中間增量備份、您將無法從最新備份中恢復應用程式。



== 當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗

如果應用程式叢集上的Astra Trident離線（並重新連線）、而且在嘗試應用程式資料管理時遇到500個內部服務錯誤、請重新啟動應用程式叢集中的所有Kubernetes節點、以還原功能。
