---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations, interoperability 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 一般限制

下列限制會影響Astra Control Service在任何支援的Kubernetes部署中對Kubernetes叢集的管理。



=== 現有連線至Postgres Pod會導致故障

當您在Postgres Pod上執行作業時、不應直接在Pod內連線以使用psql命令。Astra Control Service需要psql存取權限才能凍結及解出資料庫。如果有預先存在的連線、則快照、備份或複製都會失敗。



=== 「活動」頁面最多可顯示 100 、 000 個活動

Astra Control 活動頁面最多可顯示 100,000 個事件。若要檢視所有記錄的事件、請使用擷取事件 https://docs.netapp.com/us-en/astra-automation/["Astra Control REST API"^]。

ifdef::gcp[]



== GKE叢集的管理限制

以下限制適用於Google Kubernetes Engine（GKE）中Kubernetes叢集的管理。

endif::gcp[]



== 應用程式管理限制

下列限制會影響Astra Control Service對應用程式的管理。



=== 使用相同命名空間的多個應用程式無法一起還原至不同的命名空間

如果您管理多個使用相同命名空間的應用程式（在Astra Control中建立多個應用程式定義）、則無法將所有應用程式還原至不同的單一命名空間。您需要將每個應用程式還原至各自獨立的命名空間。



=== Astra Control不會自動指派雲端執行個體的預設值區段

Astra Control不會自動指派任何雲端執行個體的預設儲存區。您需要手動設定雲端執行個體的預設儲存區。如果未設定預設儲存區、您將無法在兩個叢集之間執行應用程式複製作業。



=== 不支援使用憑證管理程式之應用程式的就地還原作業

此版Astra Control Service不支援與憑證管理員進行就地還原應用程式。支援將作業還原至不同的命名空間和複製作業。



=== 應用程式複製在以設定的儲存類別部署應用程式之後失敗

在以明確設定的儲存類別（例如「helm install ...-set globe.storageClass = NetApp-CVs-perf-Extreme」）部署應用程式之後、後續嘗試複製應用程式時、必須讓目標叢集擁有原本指定的儲存類別。將具有明確設定儲存類別的應用程式複製到沒有相同儲存類別的叢集、將會失敗。在此案例中沒有任何恢復步驟。



=== 使用參照運算子所安裝的應用程式複製可能會失敗

Astra Control支援以命名空間範圍運算子安裝的應用程式。這些運算子通常採用「傳遞值」而非「傳遞參照」架構來設計。以下是一些遵循這些模式的營運者應用程式：

* https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
+

NOTE: 對於K8ssandra、支援就地還原作業。若要還原新命名空間或叢集的作業、必須先關閉應用程式的原始執行個體。這是為了確保傳遞的對等群組資訊不會導致跨執行個體通訊。不支援複製應用程式。

* https://github.com/jenkinsci/kubernetes-operator["Jenkins CI"^]
* https://github.com/percona/percona-xtradb-cluster-operator["Percona XtraDB叢集"^]


請注意、Astra Control可能無法複製以「逐一參考」架構設計的操作員（例如、CockroachDB操作員）。在這些類型的複製作業中、複製的操作員會嘗試從來源操作員參考Kubernetes機密、儘管在複製程序中有自己的新秘密。由於Astra Control不知道來源營運者的Kubernetes機密資料、因此複製作業可能會失敗。


NOTE: 在複製作業期間、需要IngresClass資源或Webhooks才能正常運作的應用程式、不得在目的地叢集上定義這些資源。



== 角色型存取控制（RBAC）限制

下列限制適用於Astra Control限制使用者存取資源或功能的方式。



=== 具有命名空間RBAC限制的使用者可以新增及取消管理叢集

不應允許具有命名空間RBAC限制的使用者新增或取消管理叢集。由於目前的限制、Astra無法防止此類使用者取消管理叢集。



=== 具有命名空間限制的成員使用者、必須先將命名空間新增至限制、才能存取複製或還原的應用程式

任何 `member` 具有命名空間名稱/ID之RBAC限制的使用者、可以將應用程式複製或還原至同一叢集上的新命名空間、或是組織帳戶中的任何其他叢集。不過、相同的使用者無法存取新命名空間中的複製或還原應用程式。在複製或還原作業建立新命名空間之後、帳戶管理員 / 擁有者可以編輯 `member` 使用者帳戶和更新角色限制、讓受影響的使用者能夠授予新命名空間的存取權。



=== 具有特定快照控制器版本的 Kubernetes 1.25 或更新版本叢集快照可能會失敗

如果叢集上安裝 Snapshot 控制器 API 的 v1beta1 版、執行 1.25 版或更新版本的 Kubernetes 叢集快照可能會失敗。

因應措施是在升級現有 Kubernetes 1.25 或更新版本的安裝時執行下列動作：

. 移除任何現有的 Snapshot CRD 和任何現有的 Snapshot 控制器。
. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["解除安裝Astra Trident"^]。
. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["安裝 Snapshot CRD 和 Snapshot 控制器"^]。
. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["安裝最新的 Astra Trident 版本"^]。
. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-create-a-volumesnapshotclass["建立 Volume SnapshotClass"^]。

