---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 已知問題可識別可能導致您無法成功使用本產品版本的問題。 
---
= 已知問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知問題可識別可能導致您無法成功使用本產品版本的問題。

下列已知問題會影響目前的版本：

.應用程式
* <<應用程式複製在以設定的儲存類別部署應用程式之後失敗>>
* <<當嘗試還原屬於刪除叢集的應用程式時、應用程式頁面會永久載入>>
* <<無法在已刪除和重新建立的命名空間上定義應用程式>>


.備份、還原及複製
* <<還原應用程式會導致PV大小大於原始PV>>
* <<使用特定版本的PostgreSQL時、應用程式複製失敗>>
* <<如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗>>


.其他問題
* <<使用外部Snapshotter 4.2.0版時、快照最終會開始失敗>>
* <<當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗>>




== 應用程式複製在以設定的儲存類別部署應用程式之後失敗

在以明確設定的儲存類別（例如「helm install ...-set globe.storageClass = NetApp-CVs-perf-Extreme」）部署應用程式之後、後續嘗試複製應用程式時、必須讓目標叢集擁有原本指定的儲存類別。將具有明確設定儲存類別的應用程式複製到沒有相同儲存類別的叢集、將會失敗。在此案例中沒有任何恢復步驟。



== 當嘗試還原屬於刪除叢集的應用程式時、應用程式頁面會永久載入

當您嘗試從「應用程式」頁面刪除的叢集還原應用程式時、「應用程式」頁面永遠不會完成載入。因應措施是從應用程式清單頁面的應用程式「動作」功能表還原應用程式。



== 無法在已刪除和重新建立的命名空間上定義應用程式

如果您使用命名空間定義應用程式、刪除命名空間、然後將應用程式重新安裝到同一個命名空間、則作業會失敗並顯示錯誤代碼為409。若要使用重新建立的命名空間定義應用程式、請先刪除舊的應用程式執行個體。



== 還原應用程式會導致PV大小大於原始PV

如果您在建立備份之後調整持續磁碟區的大小、然後從該備份還原、則持續磁碟區大小將會與PV的新大小相符、而非使用備份的大小。



== 使用特定版本的PostgreSQL時、應用程式複製失敗

同一個叢集內的應用程式複製作業、會持續失敗、並顯示Bitnami PostgreSQL 11.5.0圖表。若要成功複製、請使用舊版或更新版本的圖表。



== 如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗

在此案例中、備份與快照會失敗、並顯示UI 500錯誤。因應措施是重新整理應用程式清單。



== 使用外部Snapshotter 4.2.0版時、快照最終會開始失敗

使用Kubernetes Snapshot-Controller（也稱為exter-snapshotter）4.2.0版搭配Kubernetes 1.20或1.21時、快照最終可能會開始失敗。若要避免這種情況發生、請使用不同的 https://kubernetes-csi.github.io/docs/snapshot-controller.html["支援的版本"^] Kubernetes版本1.20或1.21的外部快照功能（例如4.2.1版）。



== 當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗

如果應用程式叢集上的Astra Trident離線（並重新連線）、而且在嘗試應用程式資料管理時遇到500個內部服務錯誤、請重新啟動應用程式叢集中的所有Kubernetes節點、以還原功能。
